/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { OAuthErrorReasonEnum } from '../models/oAuthErrorReasonEnum';
import { OAuthErrorTypeEnum } from '../models/oAuthErrorTypeEnum';
import { TwoFactorMethod } from '../models/twoFactorMethod';

/**
 * Creates an instance of OAuth
 */
interface OAuth {
  change_password_id?: string;
  error_description?: string;
  error?: OAuthErrorTypeEnum;
  error_uri?: string;
  two_factor_methods?: TwoFactorMethod[];
  error_reason?: OAuthErrorReasonEnum;
  two_factor_id?: string;
}

export class OAuthError extends ApiError<OAuth> {}
