/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface ActionData {
  actioneeUserId?: string;
  actionerUserId?: string;
  applicationIds?: string[];
  comment?: string;
  emailUser?: boolean;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  expiry?: bigint;
  notifyUser?: boolean;
  option?: string;
  reasonId?: string;
  userActionId?: string;
}

export const actionDataSchema: Schema<ActionData> = object({
  actioneeUserId: ['actioneeUserId', optional(string())],
  actionerUserId: ['actionerUserId', optional(string())],
  applicationIds: ['applicationIds', optional(array(string()))],
  comment: ['comment', optional(string())],
  emailUser: ['emailUser', optional(boolean())],
  expiry: ['expiry', optional(bigint())],
  notifyUser: ['notifyUser', optional(boolean())],
  option: ['option', optional(string())],
  reasonId: ['reasonId', optional(string())],
  userActionId: ['userActionId', optional(string())],
});
