/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AlgorithmEnum
 */
export enum AlgorithmEnum {
  ES256 = 'ES256',
  ES384 = 'ES384',
  ES512 = 'ES512',
  HS256 = 'HS256',
  HS384 = 'HS384',
  HS512 = 'HS512',
  PS256 = 'PS256',
  PS384 = 'PS384',
  PS512 = 'PS512',
  RS256 = 'RS256',
  RS384 = 'RS384',
  RS512 = 'RS512',
  None = 'none',
}

/**
 * Schema for AlgorithmEnum
 */
export const  algorithmEnumSchema: Schema<AlgorithmEnum> = stringEnum(AlgorithmEnum);
