/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema';

export interface APIKeyMetaData {
  attributes?: Record<string, string>;
}

export const aPIKeyMetaDataSchema: Schema<APIKeyMetaData> = object({
  attributes: ['attributes', optional(dict(string()))],
});
