/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { APIKey, aPIKeySchema } from './aPIKey';

/** Authentication key response object. */
export interface APIKeyResponse {
  /** domain POJO to represent AuthenticationKey */
  apiKey?: APIKey;
}

export const aPIKeyResponseSchema: Schema<APIKeyResponse> = object({
  apiKey: ['apiKey', optional(lazy(() => aPIKeySchema))],
});
