/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ApplicationSearchCriteria,
  applicationSearchCriteriaSchema,
} from './applicationSearchCriteria';

/** Search request for Applications */
export interface ApplicationSearchRequest {
  /** Search criteria for Applications */
  search?: ApplicationSearchCriteria;
  expand?: string[];
}

export const applicationSearchRequestSchema: Schema<ApplicationSearchRequest> = object(
  {
    search: ['search', optional(lazy(() => applicationSearchCriteriaSchema))],
    expand: ['expand', optional(array(string()))],
  }
);
