/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface AppleApplicationConfiguration {
  bundleId?: string;
  buttonText?: string;
  keyId?: string;
  scope?: string;
  servicesId?: string;
  teamId?: string;
  data?: Record<string, unknown>;
  createRegistration?: boolean;
}

export const appleApplicationConfigurationSchema: Schema<AppleApplicationConfiguration> = object(
  {
    bundleId: ['bundleId', optional(string())],
    buttonText: ['buttonText', optional(string())],
    keyId: ['keyId', optional(string())],
    scope: ['scope', optional(string())],
    servicesId: ['servicesId', optional(string())],
    teamId: ['teamId', optional(string())],
    data: ['data', optional(dict(unknown()))],
    createRegistration: ['createRegistration', optional(boolean())],
  }
);
