/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface ApplicationExternalIdentifierConfiguration {
  twoFactorTrustIdTimeToLiveInSeconds?: number;
}

export const applicationExternalIdentifierConfigurationSchema: Schema<ApplicationExternalIdentifierConfiguration> = object(
  {
    twoFactorTrustIdTimeToLiveInSeconds: [
      'twoFactorTrustIdTimeToLiveInSeconds',
      optional(number()),
    ],
  }
);
