/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  SelfServiceFormConfiguration,
  selfServiceFormConfigurationSchema,
} from './selfServiceFormConfiguration';

export interface ApplicationFormConfiguration {
  adminRegistrationFormId?: string;
  selfServiceFormConfiguration?: SelfServiceFormConfiguration;
  selfServiceFormId?: string;
}

export const applicationFormConfigurationSchema: Schema<ApplicationFormConfiguration> = object(
  {
    adminRegistrationFormId: ['adminRegistrationFormId', optional(string())],
    selfServiceFormConfiguration: [
      'selfServiceFormConfiguration',
      optional(lazy(() => selfServiceFormConfigurationSchema)),
    ],
    selfServiceFormId: ['selfServiceFormId', optional(string())],
  }
);
