/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Application, applicationSchema } from './application';

/** Application search response */
export interface ApplicationSearchResponse {
  applications?: Application[];
  total?: bigint;
  expandable?: string[];
}

export const applicationSearchResponseSchema: Schema<ApplicationSearchResponse> = object(
  {
    applications: [
      'applications',
      optional(array(lazy(() => applicationSchema))),
    ],
    total: ['total', optional(bigint())],
    expandable: ['expandable', optional(array(string()))],
  }
);
