/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TimeBasedDeletePolicy,
  timeBasedDeletePolicySchema,
} from './timeBasedDeletePolicy';

/** A Application-level policy for deleting Users. */
export interface ApplicationRegistrationDeletePolicy {
  /** A policy for deleting Users based upon some external criteria. */
  unverified?: TimeBasedDeletePolicy;
}

export const applicationRegistrationDeletePolicySchema: Schema<ApplicationRegistrationDeletePolicy> = object(
  {
    unverified: [
      'unverified',
      optional(lazy(() => timeBasedDeletePolicySchema)),
    ],
  }
);
