/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApplicationAccessControlConfiguration {
  uiIPAccessControlListId?: string;
}

export const applicationAccessControlConfigurationSchema: Schema<ApplicationAccessControlConfiguration> = object(
  { uiIPAccessControlListId: ['uiIPAccessControlListId', optional(string())] }
);
