/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AttestationConveyancePreferenceEnum
 */
export enum AttestationConveyancePreferenceEnum {
  None = 'none',
  Indirect = 'indirect',
  Direct = 'direct',
  Enterprise = 'enterprise',
}

/**
 * Schema for AttestationConveyancePreferenceEnum
 */
export const  attestationConveyancePreferenceEnumSchema: Schema<AttestationConveyancePreferenceEnum> = stringEnum(AttestationConveyancePreferenceEnum);
