/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AuditLog, auditLogSchema } from './auditLog';

/** Audit log response. */
export interface AuditLogResponse {
  /** An audit log. */
  auditLog?: AuditLog;
}

export const auditLogResponseSchema: Schema<AuditLogResponse> = object({
  auditLog: ['auditLog', optional(lazy(() => auditLogSchema))],
});
