/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AuditLog, auditLogSchema } from './auditLog';
import { EventInfo, eventInfoSchema } from './eventInfo';

export interface AuditLogRequest {
  /** An audit log. */
  auditLog?: AuditLog;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const auditLogRequestSchema: Schema<AuditLogRequest> = object({
  auditLog: ['auditLog', optional(lazy(() => auditLogSchema))],
  eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))],
});
