/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { AuditLog, auditLogSchema } from './auditLog';

/** Audit log response. */
export interface AuditLogSearchResponse {
  auditLogs?: AuditLog[];
  total?: bigint;
}

export const auditLogSearchResponseSchema: Schema<AuditLogSearchResponse> = object(
  {
    auditLogs: ['auditLogs', optional(array(lazy(() => auditLogSchema)))],
    total: ['total', optional(bigint())],
  }
);
