/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  DeleteConfiguration,
  deleteConfigurationSchema,
} from './deleteConfiguration';

export interface AuditLogConfiguration {
  mDelete?: DeleteConfiguration;
}

export const auditLogConfigurationSchema: Schema<AuditLogConfiguration> = object(
  { mDelete: ['delete', optional(lazy(() => deleteConfigurationSchema))] }
);
