/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  AuditLogSearchCriteria,
  auditLogSearchCriteriaSchema,
} from './auditLogSearchCriteria';

export interface AuditLogExportRequest {
  criteria?: AuditLogSearchCriteria;
  dateTimeSecondsFormat?: string;
  /** Timezone Identifier */
  zoneId?: string;
}

export const auditLogExportRequestSchema: Schema<AuditLogExportRequest> = object(
  {
    criteria: ['criteria', optional(lazy(() => auditLogSearchCriteriaSchema))],
    dateTimeSecondsFormat: ['dateTimeSecondsFormat', optional(string())],
    zoneId: ['zoneId', optional(string())],
  }
);
