/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthenticatorAttachmentPreferenceEnum
 */
export enum AuthenticatorAttachmentPreferenceEnum {
  Any = 'any',
  Platform = 'platform',
  CrossPlatform = 'crossPlatform',
}

/**
 * Schema for AuthenticatorAttachmentPreferenceEnum
 */
export const  authenticatorAttachmentPreferenceEnumSchema: Schema<AuthenticatorAttachmentPreferenceEnum> = stringEnum(AuthenticatorAttachmentPreferenceEnum);
