/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, dict, object, optional, Schema, unknown } from '../schema';

export interface BaseIdentityProviderApplicationConfiguration {
  data?: Record<string, unknown>;
  createRegistration?: boolean;
  enabled?: boolean;
}

export const baseIdentityProviderApplicationConfigurationSchema: Schema<BaseIdentityProviderApplicationConfiguration> = object(
  {
    data: ['data', optional(dict(unknown()))],
    createRegistration: ['createRegistration', optional(boolean())],
    enabled: ['enabled', optional(boolean())],
  }
);
