/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { SortField, sortFieldSchema } from './sortField';

export interface BaseElasticSearchCriteria {
  accurateTotal?: boolean;
  ids?: string[];
  nextResults?: string;
  query?: string;
  queryString?: string;
  sortFields?: SortField[];
  numberOfResults?: number;
  orderBy?: string;
  startRow?: number;
}

export const baseElasticSearchCriteriaSchema: Schema<BaseElasticSearchCriteria> = object(
  {
    accurateTotal: ['accurateTotal', optional(boolean())],
    ids: ['ids', optional(array(string()))],
    nextResults: ['nextResults', optional(string())],
    query: ['query', optional(string())],
    queryString: ['queryString', optional(string())],
    sortFields: ['sortFields', optional(array(lazy(() => sortFieldSchema)))],
    numberOfResults: ['numberOfResults', optional(number())],
    orderBy: ['orderBy', optional(string())],
    startRow: ['startRow', optional(number())],
  }
);
