/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BreachActionEnum
 */
export enum BreachActionEnum {
  Off = 'Off',
  RecordOnly = 'RecordOnly',
  NotifyUser = 'NotifyUser',
  RequireChange = 'RequireChange',
}

/**
 * Schema for BreachActionEnum
 */
export const  breachActionEnumSchema: Schema<BreachActionEnum> = stringEnum(BreachActionEnum);
