/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CaptchaMethodEnum
 */
export enum CaptchaMethodEnum {
  GoogleRecaptchaV2 = 'GoogleRecaptchaV2',
  GoogleRecaptchaV3 = 'GoogleRecaptchaV3',
  HCaptcha = 'HCaptcha',
  HCaptchaEnterprise = 'HCaptchaEnterprise',
}

/**
 * Schema for CaptchaMethodEnum
 */
export const  captchaMethodEnumSchema: Schema<CaptchaMethodEnum> = stringEnum(CaptchaMethodEnum);
