/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ChangePasswordReasonEnum
 */
export enum ChangePasswordReasonEnum {
  Administrative = 'Administrative',
  Breached = 'Breached',
  Expired = 'Expired',
  Validation = 'Validation',
}

/**
 * Schema for ChangePasswordReasonEnum
 */
export const  changePasswordReasonEnumSchema: Schema<ChangePasswordReasonEnum> = stringEnum(ChangePasswordReasonEnum);
