/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string, unknown } from '../schema';

/** Change password response object. */
export interface ChangePasswordResponse {
  oneTimePassword?: string;
  state?: Record<string, unknown>;
}

export const changePasswordResponseSchema: Schema<ChangePasswordResponse> = object(
  {
    oneTimePassword: ['oneTimePassword', optional(string())],
    state: ['state', optional(dict(unknown()))],
  }
);
