/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';

/** Change password request object. */
export interface ChangePasswordRequest {
  applicationId?: string;
  changePasswordId?: string;
  currentPassword?: string;
  loginId?: string;
  password?: string;
  refreshToken?: string;
  trustChallenge?: string;
  trustToken?: string;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const changePasswordRequestSchema: Schema<ChangePasswordRequest> = object(
  {
    applicationId: ['applicationId', optional(string())],
    changePasswordId: ['changePasswordId', optional(string())],
    currentPassword: ['currentPassword', optional(string())],
    loginId: ['loginId', optional(string())],
    password: ['password', optional(string())],
    refreshToken: ['refreshToken', optional(string())],
    trustChallenge: ['trustChallenge', optional(string())],
    trustToken: ['trustToken', optional(string())],
    eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))],
  }
);
