/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  UsernameModeration,
  usernameModerationSchema,
} from './usernameModeration';

/** CleanSpeak configuration at the system and application level. */
export interface CleanSpeakConfiguration {
  apiKey?: string;
  applicationIds?: string[];
  url?: string;
  usernameModeration?: UsernameModeration;
  enabled?: boolean;
}

export const cleanSpeakConfigurationSchema: Schema<CleanSpeakConfiguration> = object(
  {
    apiKey: ['apiKey', optional(string())],
    applicationIds: ['applicationIds', optional(array(string()))],
    url: ['url', optional(string())],
    usernameModeration: [
      'usernameModeration',
      optional(lazy(() => usernameModerationSchema)),
    ],
    enabled: ['enabled', optional(boolean())],
  }
);
