/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ClientAuthenticationMethodEnum
 */
export enum ClientAuthenticationMethodEnum {
  None = 'none',
  ClientSecretBasic = 'client_secret_basic',
  ClientSecretPost = 'client_secret_post',
}

/**
 * Schema for ClientAuthenticationMethodEnum
 */
export const  clientAuthenticationMethodEnumSchema: Schema<ClientAuthenticationMethodEnum> = stringEnum(ClientAuthenticationMethodEnum);
