/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  BaseConnectorConfiguration,
  baseConnectorConfigurationSchema,
} from './baseConnectorConfiguration';

export interface ConnectorRequest {
  /** Do not require a setter for 'type', it is defined by the concrete class and is not mutable */
  connector?: BaseConnectorConfiguration;
}

export const connectorRequestSchema: Schema<ConnectorRequest> = object({
  connector: [
    'connector',
    optional(lazy(() => baseConnectorConfigurationSchema)),
  ],
});
