/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConsentStatusEnum
 */
export enum ConsentStatusEnum {
  Active = 'Active',
  Revoked = 'Revoked',
}

/**
 * Schema for ConsentStatusEnum
 */
export const  consentStatusEnumSchema: Schema<ConsentStatusEnum> = stringEnum(ConsentStatusEnum);
