/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { Consent, consentSchema } from './consent';

/** Consent search response */
export interface ConsentSearchResponse {
  consents?: Consent[];
  total?: bigint;
}

export const consentSearchResponseSchema: Schema<ConsentSearchResponse> = object(
  {
    consents: ['consents', optional(array(lazy(() => consentSchema)))],
    total: ['total', optional(bigint())],
  }
);
