/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CoseEllipticCurveEnum
 */
export enum CoseEllipticCurveEnum {
  Reserved = 'Reserved',
  P256 = 'P256',
  P384 = 'P384',
  P521 = 'P521',
  X25519 = 'X25519',
  X448 = 'X448',
  Ed25519 = 'Ed25519',
  Ed448 = 'Ed448',
  Secp256k1 = 'Secp256k1',
}

/**
 * Schema for CoseEllipticCurveEnum
 */
export const  coseEllipticCurveEnumSchema: Schema<CoseEllipticCurveEnum> = stringEnum(CoseEllipticCurveEnum);
