/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CoseKeyTypeEnum
 */
export enum CoseKeyTypeEnum {
  Reserved = 'Reserved',
  OKP = 'OKP',
  EC2 = 'EC2',
  RSA = 'RSA',
  Symmetric = 'Symmetric',
}

/**
 * Schema for CoseKeyTypeEnum
 */
export const  coseKeyTypeEnumSchema: Schema<CoseKeyTypeEnum> = stringEnum(CoseKeyTypeEnum);
