/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** Contains the output for the {@code credProps} extension */
export interface CredentialPropertiesOutput {
  rk?: boolean;
}

export const credentialPropertiesOutputSchema: Schema<CredentialPropertiesOutput> = object(
  { rk: ['rk', optional(boolean())] }
);
