/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { DeviceInfo, deviceInfoSchema } from './deviceInfo';
import { PendingIdPLink, pendingIdPLinkSchema } from './pendingIdPLink';

export interface DeviceUserCodeResponse {
  clientId?: string;
  deviceInfo?: DeviceInfo;
  expiresIn?: number;
  pendingIdPLink?: PendingIdPLink;
  scope?: string;
  tenantId?: string;
  userCode?: string;
}

export const deviceUserCodeResponseSchema: Schema<DeviceUserCodeResponse> = object(
  {
    clientId: ['client_id', optional(string())],
    deviceInfo: ['deviceInfo', optional(lazy(() => deviceInfoSchema))],
    expiresIn: ['expires_in', optional(number())],
    pendingIdPLink: [
      'pendingIdPLink',
      optional(lazy(() => pendingIdPLinkSchema)),
    ],
    scope: ['scope', optional(string())],
    tenantId: ['tenantId', optional(string())],
    userCode: ['user_code', optional(string())],
  }
);
