/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DeviceResponse {
  deviceCode?: string;
  expiresIn?: number;
  interval?: number;
  userCode?: string;
  verificationUri?: string;
  verificationUriComplete?: string;
}

export const deviceResponseSchema: Schema<DeviceResponse> = object({
  deviceCode: ['device_code', optional(string())],
  expiresIn: ['expires_in', optional(number())],
  interval: ['interval', optional(number())],
  userCode: ['user_code', optional(string())],
  verificationUri: ['verification_uri', optional(string())],
  verificationUriComplete: ['verification_uri_complete', optional(string())],
});
