/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeviceTypeEnum
 */
export enum DeviceTypeEnum {
  BROWSER = 'BROWSER',
  DESKTOP = 'DESKTOP',
  LAPTOP = 'LAPTOP',
  MOBILE = 'MOBILE',
  OTHER = 'OTHER',
  SERVER = 'SERVER',
  TABLET = 'TABLET',
  TV = 'TV',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Schema for DeviceTypeEnum
 */
export const  deviceTypeEnumSchema: Schema<DeviceTypeEnum> = stringEnum(DeviceTypeEnum);
