/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { EmailTemplate, emailTemplateSchema } from './emailTemplate';

/** Email template search response */
export interface EmailTemplateSearchResponse {
  emailTemplates?: EmailTemplate[];
  total?: bigint;
}

export const emailTemplateSearchResponseSchema: Schema<EmailTemplateSearchResponse> = object(
  {
    emailTemplates: [
      'emailTemplates',
      optional(array(lazy(() => emailTemplateSchema))),
    ],
    total: ['total', optional(bigint())],
  }
);
