/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { EmailTemplate, emailTemplateSchema } from './emailTemplate';

/** Email template request. */
export interface EmailTemplateRequest {
  /** Stores an email template used to send emails to users. */
  emailTemplate?: EmailTemplate;
}

export const emailTemplateRequestSchema: Schema<EmailTemplateRequest> = object({
  emailTemplate: ['emailTemplate', optional(lazy(() => emailTemplateSchema))],
});
