/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  EmailTemplateSearchCriteria,
  emailTemplateSearchCriteriaSchema,
} from './emailTemplateSearchCriteria';

/** Search request for email templates */
export interface EmailTemplateSearchRequest {
  /** Search criteria for Email templates */
  search?: EmailTemplateSearchCriteria;
}

export const emailTemplateSearchRequestSchema: Schema<EmailTemplateSearchRequest> = object(
  {
    search: ['search', optional(lazy(() => emailTemplateSearchCriteriaSchema))],
  }
);
