/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Attachment, attachmentSchema } from './attachment';
import { EmailAddress, emailAddressSchema } from './emailAddress';

/** This class is an abstraction of a simple email message. */
export interface Email {
  attachments?: Attachment[];
  bcc?: EmailAddress[];
  cc?: EmailAddress[];
  /** An email address. */
  from?: EmailAddress;
  html?: string;
  /** An email address. */
  replyTo?: EmailAddress;
  subject?: string;
  text?: string;
  to?: EmailAddress[];
}

export const emailSchema: Schema<Email> = object({
  attachments: ['attachments', optional(array(lazy(() => attachmentSchema)))],
  bcc: ['bcc', optional(array(lazy(() => emailAddressSchema)))],
  cc: ['cc', optional(array(lazy(() => emailAddressSchema)))],
  from: ['from', optional(lazy(() => emailAddressSchema))],
  html: ['html', optional(string())],
  replyTo: ['replyTo', optional(lazy(() => emailAddressSchema))],
  subject: ['subject', optional(string())],
  text: ['text', optional(string())],
  to: ['to', optional(array(lazy(() => emailAddressSchema)))],
});
