/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string, unknown } from '../schema';

/** Stores an email template used to send emails to users. */
export interface EmailTemplate {
  defaultFromName?: string;
  defaultHtmlTemplate?: string;
  defaultSubject?: string;
  defaultTextTemplate?: string;
  fromEmail?: string;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  /** Models a set of localized Strings that can be stored as JSON. */
  localizedFromNames?: unknown;
  /** Models a set of localized Strings that can be stored as JSON. */
  localizedHtmlTemplates?: unknown;
  /** Models a set of localized Strings that can be stored as JSON. */
  localizedSubjects?: unknown;
  /** Models a set of localized Strings that can be stored as JSON. */
  localizedTextTemplates?: unknown;
  name?: string;
}

export const emailTemplateSchema: Schema<EmailTemplate> = object({
  defaultFromName: ['defaultFromName', optional(string())],
  defaultHtmlTemplate: ['defaultHtmlTemplate', optional(string())],
  defaultSubject: ['defaultSubject', optional(string())],
  defaultTextTemplate: ['defaultTextTemplate', optional(string())],
  fromEmail: ['fromEmail', optional(string())],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
  localizedFromNames: ['localizedFromNames', optional(unknown())],
  localizedHtmlTemplates: ['localizedHtmlTemplates', optional(unknown())],
  localizedSubjects: ['localizedSubjects', optional(unknown())],
  localizedTextTemplates: ['localizedTextTemplates', optional(unknown())],
  name: ['name', optional(string())],
});
