/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  EntityGrantSearchCriteria,
  entityGrantSearchCriteriaSchema,
} from './entityGrantSearchCriteria';

/** Search request for entity grants. */
export interface EntityGrantSearchRequest {
  /** Search criteria for entity grants. */
  search?: EntityGrantSearchCriteria;
}

export const entityGrantSearchRequestSchema: Schema<EntityGrantSearchRequest> = object(
  { search: ['search', optional(lazy(() => entityGrantSearchCriteriaSchema))] }
);
