/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Entity, entitySchema } from './entity';

/** Entity API request object. */
export interface EntityRequest {
  /** Models an entity that a user can be granted permissions to. Or an entity that can be granted permissions to another entity. */
  entity?: Entity;
}

export const entityRequestSchema: Schema<EntityRequest> = object({
  entity: ['entity', optional(lazy(() => entitySchema))],
});
