/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { EntityType, entityTypeSchema } from './entityType';

/** Models an entity that a user can be granted permissions to. Or an entity that can be granted permissions to another entity. */
export interface Entity {
  data?: Record<string, unknown>;
  clientId?: string;
  clientSecret?: string;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  name?: string;
  parentId?: string;
  tenantId?: string;
  /** Models an entity type that has a specific set of permissions. These are global objects and can be used across tenants. */
  type?: EntityType;
}

export const entitySchema: Schema<Entity> = object({
  data: ['data', optional(dict(unknown()))],
  clientId: ['clientId', optional(string())],
  clientSecret: ['clientSecret', optional(string())],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
  name: ['name', optional(string())],
  parentId: ['parentId', optional(string())],
  tenantId: ['tenantId', optional(string())],
  type: ['type', optional(lazy(() => entityTypeSchema))],
});
