/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  EntitySearchCriteria,
  entitySearchCriteriaSchema,
} from './entitySearchCriteria';

/** Search request for entities */
export interface EntitySearchRequest {
  /** This class is the entity query. It provides a build pattern as well as public fields for use on forms and in actions. */
  search?: EntitySearchCriteria;
}

export const entitySearchRequestSchema: Schema<EntitySearchRequest> = object({
  search: ['search', optional(lazy(() => entitySearchCriteriaSchema))],
});
