/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  dict,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

/** Models a specific entity type permission. This permission can be granted to users or other entities. */
export interface EntityTypePermission {
  data?: Record<string, unknown>;
  description?: string;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  isDefault?: boolean;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  name?: string;
}

export const entityTypePermissionSchema: Schema<EntityTypePermission> = object({
  data: ['data', optional(dict(unknown()))],
  description: ['description', optional(string())],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  isDefault: ['isDefault', optional(boolean())],
  lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
  name: ['name', optional(string())],
});
