/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Search criteria for entity types. */
export interface EntityTypeSearchCriteria {
  name?: string;
  numberOfResults?: number;
  orderBy?: string;
  startRow?: number;
}

export const entityTypeSearchCriteriaSchema: Schema<EntityTypeSearchCriteria> = object(
  {
    name: ['name', optional(string())],
    numberOfResults: ['numberOfResults', optional(number())],
    orderBy: ['orderBy', optional(string())],
    startRow: ['startRow', optional(number())],
  }
);
