/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

/** JWT Configuration for entities. */
export interface EntityJWTConfiguration {
  accessTokenKeyId?: string;
  timeToLiveInSeconds?: number;
  enabled?: boolean;
}

export const entityJWTConfigurationSchema: Schema<EntityJWTConfiguration> = object(
  {
    accessTokenKeyId: ['accessTokenKeyId', optional(string())],
    timeToLiveInSeconds: ['timeToLiveInSeconds', optional(number())],
    enabled: ['enabled', optional(boolean())],
  }
);
