/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Entity, entitySchema } from './entity';

/** Search request for entities */
export interface EntitySearchResponse {
  entities?: Entity[];
  nextResults?: string;
  total?: bigint;
}

export const entitySearchResponseSchema: Schema<EntitySearchResponse> = object({
  entities: ['entities', optional(array(lazy(() => entitySchema)))],
  nextResults: ['nextResults', optional(string())],
  total: ['total', optional(bigint())],
});
