/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Error, errorSchema } from './error';

/** Standard error domain object that can also be used as the response from an API call. */
export interface Errors {
  fieldErrors?: Error[];
  generalErrors?: Error[];
}

export const errorsSchema: Schema<Errors> = object({
  fieldErrors: ['fieldErrors', optional(array(lazy(() => errorSchema)))],
  generalErrors: ['generalErrors', optional(array(lazy(() => errorSchema)))],
});
