/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';
import { EventLogTypeEnum, eventLogTypeEnumSchema } from './eventLogTypeEnum';

/** Event log used internally by FusionAuth to help developers debug hooks, Webhooks, email templates, etc. */
export interface EventLog {
  id?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  message?: string;
  /** Event Log Type */
  type?: EventLogTypeEnum;
}

export const eventLogSchema: Schema<EventLog> = object({
  id: ['id', optional(bigint())],
  insertInstant: ['insertInstant', optional(bigint())],
  message: ['message', optional(string())],
  type: ['type', optional(eventLogTypeEnumSchema)],
});
