/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { BaseEvent, baseEventSchema } from './baseEvent';

/** Container for the event information. This is the JSON that is sent from FusionAuth to webhooks. */
export interface EventRequest {
  /** Base-class for all FusionAuth events. */
  event?: BaseEvent;
}

export const eventRequestSchema: Schema<EventRequest> = object({
  event: ['event', optional(lazy(() => baseEventSchema))],
});
