/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema } from '../schema';
import {
  EventConfigurationData,
  eventConfigurationDataSchema,
} from './eventConfigurationData';

export interface EventConfiguration {
  events?: Record<string, EventConfigurationData>;
}

export const eventConfigurationSchema: Schema<EventConfiguration> = object({
  events: ['events', optional(dict(lazy(() => eventConfigurationDataSchema)))],
});
