/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EventTypeEnum
 */
export enum EventTypeEnum {
  JWTPublicKeyUpdate = 'JWTPublicKeyUpdate',
  JWTRefreshTokenRevoke = 'JWTRefreshTokenRevoke',
  JWTRefresh = 'JWTRefresh',
  AuditLogCreate = 'AuditLogCreate',
  EventLogCreate = 'EventLogCreate',
  KickstartSuccess = 'KickstartSuccess',
  GroupCreate = 'GroupCreate',
  GroupCreateComplete = 'GroupCreateComplete',
  GroupDelete = 'GroupDelete',
  GroupDeleteComplete = 'GroupDeleteComplete',
  GroupMemberAdd = 'GroupMemberAdd',
  GroupMemberAddComplete = 'GroupMemberAddComplete',
  GroupMemberRemove = 'GroupMemberRemove',
  GroupMemberRemoveComplete = 'GroupMemberRemoveComplete',
  GroupMemberUpdate = 'GroupMemberUpdate',
  GroupMemberUpdateComplete = 'GroupMemberUpdateComplete',
  GroupUpdate = 'GroupUpdate',
  GroupUpdateComplete = 'GroupUpdateComplete',
  UserAction = 'UserAction',
  UserBulkCreate = 'UserBulkCreate',
  UserCreate = 'UserCreate',
  UserCreateComplete = 'UserCreateComplete',
  UserDeactivate = 'UserDeactivate',
  UserDelete = 'UserDelete',
  UserDeleteComplete = 'UserDeleteComplete',
  UserEmailUpdate = 'UserEmailUpdate',
  UserEmailVerified = 'UserEmailVerified',
  UserIdentityProviderLink = 'UserIdentityProviderLink',
  UserIdentityProviderUnlink = 'UserIdentityProviderUnlink',
  UserLoginIdDuplicateOnCreate = 'UserLoginIdDuplicateOnCreate',
  UserLoginIdDuplicateOnUpdate = 'UserLoginIdDuplicateOnUpdate',
  UserLoginFailed = 'UserLoginFailed',
  UserLoginNewDevice = 'UserLoginNewDevice',
  UserLoginSuccess = 'UserLoginSuccess',
  UserLoginSuspicious = 'UserLoginSuspicious',
  UserPasswordBreach = 'UserPasswordBreach',
  UserPasswordResetSend = 'UserPasswordResetSend',
  UserPasswordResetStart = 'UserPasswordResetStart',
  UserPasswordResetSuccess = 'UserPasswordResetSuccess',
  UserPasswordUpdate = 'UserPasswordUpdate',
  UserReactivate = 'UserReactivate',
  UserRegistrationCreate = 'UserRegistrationCreate',
  UserRegistrationCreateComplete = 'UserRegistrationCreateComplete',
  UserRegistrationDelete = 'UserRegistrationDelete',
  UserRegistrationDeleteComplete = 'UserRegistrationDeleteComplete',
  UserRegistrationUpdate = 'UserRegistrationUpdate',
  UserRegistrationUpdateComplete = 'UserRegistrationUpdateComplete',
  UserRegistrationVerified = 'UserRegistrationVerified',
  UserTwoFactorMethodAdd = 'UserTwoFactorMethodAdd',
  UserTwoFactorMethodRemove = 'UserTwoFactorMethodRemove',
  UserUpdate = 'UserUpdate',
  UserUpdateComplete = 'UserUpdateComplete',
  Test = 'Test',
}

/**
 * Schema for EventTypeEnum
 */
export const  eventTypeEnumSchema: Schema<EventTypeEnum> = stringEnum(EventTypeEnum);
