/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';
import { EventLogTypeEnum, eventLogTypeEnumSchema } from './eventLogTypeEnum';

/** Search criteria for the event log. */
export interface EventLogSearchCriteria {
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  end?: bigint;
  message?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  start?: bigint;
  /** Event Log Type */
  type?: EventLogTypeEnum;
  numberOfResults?: number;
  orderBy?: string;
  startRow?: number;
}

export const eventLogSearchCriteriaSchema: Schema<EventLogSearchCriteria> = object(
  {
    end: ['end', optional(bigint())],
    message: ['message', optional(string())],
    start: ['start', optional(bigint())],
    type: ['type', optional(eventLogTypeEnumSchema)],
    numberOfResults: ['numberOfResults', optional(number())],
    orderBy: ['orderBy', optional(string())],
    startRow: ['startRow', optional(number())],
  }
);
