/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import {
  TransactionTypeEnum,
  transactionTypeEnumSchema,
} from './transactionTypeEnum';

export interface EventConfigurationData {
  /** The transaction types for Webhooks and other event systems within FusionAuth. */
  transactionType?: TransactionTypeEnum;
  enabled?: boolean;
}

export const eventConfigurationDataSchema: Schema<EventConfigurationData> = object(
  {
    transactionType: ['transactionType', optional(transactionTypeEnumSchema)],
    enabled: ['enabled', optional(boolean())],
  }
);
