/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExpiryUnitEnum
 */
export enum ExpiryUnitEnum {
  MINUTES = 'MINUTES',
  HOURS = 'HOURS',
  DAYS = 'DAYS',
  WEEKS = 'WEEKS',
  MONTHS = 'MONTHS',
  YEARS = 'YEARS',
}

/**
 * Schema for ExpiryUnitEnum
 */
export const  expiryUnitEnumSchema: Schema<ExpiryUnitEnum> = stringEnum(ExpiryUnitEnum);
