/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import {
  SecureGeneratorConfiguration,
  secureGeneratorConfigurationSchema,
} from './secureGeneratorConfiguration';

export interface ExternalIdentifierConfiguration {
  authorizationGrantIdTimeToLiveInSeconds?: number;
  changePasswordIdGenerator?: SecureGeneratorConfiguration;
  changePasswordIdTimeToLiveInSeconds?: number;
  deviceCodeTimeToLiveInSeconds?: number;
  deviceUserCodeIdGenerator?: SecureGeneratorConfiguration;
  emailVerificationIdGenerator?: SecureGeneratorConfiguration;
  emailVerificationIdTimeToLiveInSeconds?: number;
  emailVerificationOneTimeCodeGenerator?: SecureGeneratorConfiguration;
  externalAuthenticationIdTimeToLiveInSeconds?: number;
  oneTimePasswordTimeToLiveInSeconds?: number;
  passwordlessLoginGenerator?: SecureGeneratorConfiguration;
  passwordlessLoginTimeToLiveInSeconds?: number;
  pendingAccountLinkTimeToLiveInSeconds?: number;
  registrationVerificationIdGenerator?: SecureGeneratorConfiguration;
  registrationVerificationIdTimeToLiveInSeconds?: number;
  registrationVerificationOneTimeCodeGenerator?: SecureGeneratorConfiguration;
  rememberOAuthScopeConsentChoiceTimeToLiveInSeconds?: number;
  samlv2AuthNRequestIdTimeToLiveInSeconds?: number;
  setupPasswordIdGenerator?: SecureGeneratorConfiguration;
  setupPasswordIdTimeToLiveInSeconds?: number;
  trustTokenTimeToLiveInSeconds?: number;
  twoFactorIdTimeToLiveInSeconds?: number;
  twoFactorOneTimeCodeIdGenerator?: SecureGeneratorConfiguration;
  twoFactorOneTimeCodeIdTimeToLiveInSeconds?: number;
  twoFactorTrustIdTimeToLiveInSeconds?: number;
  webAuthnAuthenticationChallengeTimeToLiveInSeconds?: number;
  webAuthnRegistrationChallengeTimeToLiveInSeconds?: number;
}

export const externalIdentifierConfigurationSchema: Schema<ExternalIdentifierConfiguration> = object(
  {
    authorizationGrantIdTimeToLiveInSeconds: [
      'authorizationGrantIdTimeToLiveInSeconds',
      optional(number()),
    ],
    changePasswordIdGenerator: [
      'changePasswordIdGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    changePasswordIdTimeToLiveInSeconds: [
      'changePasswordIdTimeToLiveInSeconds',
      optional(number()),
    ],
    deviceCodeTimeToLiveInSeconds: [
      'deviceCodeTimeToLiveInSeconds',
      optional(number()),
    ],
    deviceUserCodeIdGenerator: [
      'deviceUserCodeIdGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    emailVerificationIdGenerator: [
      'emailVerificationIdGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    emailVerificationIdTimeToLiveInSeconds: [
      'emailVerificationIdTimeToLiveInSeconds',
      optional(number()),
    ],
    emailVerificationOneTimeCodeGenerator: [
      'emailVerificationOneTimeCodeGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    externalAuthenticationIdTimeToLiveInSeconds: [
      'externalAuthenticationIdTimeToLiveInSeconds',
      optional(number()),
    ],
    oneTimePasswordTimeToLiveInSeconds: [
      'oneTimePasswordTimeToLiveInSeconds',
      optional(number()),
    ],
    passwordlessLoginGenerator: [
      'passwordlessLoginGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    passwordlessLoginTimeToLiveInSeconds: [
      'passwordlessLoginTimeToLiveInSeconds',
      optional(number()),
    ],
    pendingAccountLinkTimeToLiveInSeconds: [
      'pendingAccountLinkTimeToLiveInSeconds',
      optional(number()),
    ],
    registrationVerificationIdGenerator: [
      'registrationVerificationIdGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    registrationVerificationIdTimeToLiveInSeconds: [
      'registrationVerificationIdTimeToLiveInSeconds',
      optional(number()),
    ],
    registrationVerificationOneTimeCodeGenerator: [
      'registrationVerificationOneTimeCodeGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    rememberOAuthScopeConsentChoiceTimeToLiveInSeconds: [
      'rememberOAuthScopeConsentChoiceTimeToLiveInSeconds',
      optional(number()),
    ],
    samlv2AuthNRequestIdTimeToLiveInSeconds: [
      'samlv2AuthNRequestIdTimeToLiveInSeconds',
      optional(number()),
    ],
    setupPasswordIdGenerator: [
      'setupPasswordIdGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    setupPasswordIdTimeToLiveInSeconds: [
      'setupPasswordIdTimeToLiveInSeconds',
      optional(number()),
    ],
    trustTokenTimeToLiveInSeconds: [
      'trustTokenTimeToLiveInSeconds',
      optional(number()),
    ],
    twoFactorIdTimeToLiveInSeconds: [
      'twoFactorIdTimeToLiveInSeconds',
      optional(number()),
    ],
    twoFactorOneTimeCodeIdGenerator: [
      'twoFactorOneTimeCodeIdGenerator',
      optional(lazy(() => secureGeneratorConfigurationSchema)),
    ],
    twoFactorOneTimeCodeIdTimeToLiveInSeconds: [
      'twoFactorOneTimeCodeIdTimeToLiveInSeconds',
      optional(number()),
    ],
    twoFactorTrustIdTimeToLiveInSeconds: [
      'twoFactorTrustIdTimeToLiveInSeconds',
      optional(number()),
    ],
    webAuthnAuthenticationChallengeTimeToLiveInSeconds: [
      'webAuthnAuthenticationChallengeTimeToLiveInSeconds',
      optional(number()),
    ],
    webAuthnRegistrationChallengeTimeToLiveInSeconds: [
      'webAuthnRegistrationChallengeTimeToLiveInSeconds',
      optional(number()),
    ],
  }
);
