/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, dict, object, optional, Schema, unknown } from '../schema';

export interface ExternalJWTApplicationConfiguration {
  data?: Record<string, unknown>;
  createRegistration?: boolean;
}

export const externalJWTApplicationConfigurationSchema: Schema<ExternalJWTApplicationConfiguration> = object(
  {
    data: ['data', optional(dict(unknown()))],
    createRegistration: ['createRegistration', optional(boolean())],
  }
);
