/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** A policy to configure if and when the user-action is canceled prior to the expiration of the action. */
export interface FailedAuthenticationActionCancelPolicy {
  onPasswordReset?: boolean;
}

export const failedAuthenticationActionCancelPolicySchema: Schema<FailedAuthenticationActionCancelPolicy> = object(
  { onPasswordReset: ['onPasswordReset', optional(boolean())] }
);
