/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ExpiryUnitEnum, expiryUnitEnumSchema } from './expiryUnitEnum';
import {
  FailedAuthenticationActionCancelPolicy,
  failedAuthenticationActionCancelPolicySchema,
} from './failedAuthenticationActionCancelPolicy';

/** Configuration for the behavior of failed login attempts. This helps us protect against brute force password attacks. */
export interface FailedAuthenticationConfiguration {
  /** A policy to configure if and when the user-action is canceled prior to the expiration of the action. */
  actionCancelPolicy?: FailedAuthenticationActionCancelPolicy;
  actionDuration?: bigint;
  actionDurationUnit?: ExpiryUnitEnum;
  emailUser?: boolean;
  resetCountInSeconds?: number;
  tooManyAttempts?: number;
  userActionId?: string;
}

export const failedAuthenticationConfigurationSchema: Schema<FailedAuthenticationConfiguration> = object(
  {
    actionCancelPolicy: [
      'actionCancelPolicy',
      optional(lazy(() => failedAuthenticationActionCancelPolicySchema)),
    ],
    actionDuration: ['actionDuration', optional(bigint())],
    actionDurationUnit: ['actionDurationUnit', optional(expiryUnitEnumSchema)],
    emailUser: ['emailUser', optional(boolean())],
    resetCountInSeconds: ['resetCountInSeconds', optional(number())],
    tooManyAttempts: ['tooManyAttempts', optional(number())],
    userActionId: ['userActionId', optional(string())],
  }
);
