/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FamilyRoleEnum
 */
export enum FamilyRoleEnum {
  Child = 'Child',
  Teen = 'Teen',
  Adult = 'Adult',
}

/**
 * Schema for FamilyRoleEnum
 */
export const  familyRoleEnumSchema: Schema<FamilyRoleEnum> = stringEnum(FamilyRoleEnum);
