/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { FamilyMember, familyMemberSchema } from './familyMember';

/** API request for managing families and members. */
export interface FamilyRequest {
  /** Models a single family member. */
  familyMember?: FamilyMember;
}

export const familyRequestSchema: Schema<FamilyRequest> = object({
  familyMember: ['familyMember', optional(lazy(() => familyMemberSchema))],
});
