/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { FormField, formFieldSchema } from './formField';

/** Form field response. */
export interface FormFieldResponse {
  field?: FormField;
  fields?: FormField[];
}

export const formFieldResponseSchema: Schema<FormFieldResponse> = object({
  field: ['field', optional(lazy(() => formFieldSchema))],
  fields: ['fields', optional(array(lazy(() => formFieldSchema)))],
});
