/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { FormField, formFieldSchema } from './formField';

/** The FormField API request object. */
export interface FormFieldRequest {
  field?: FormField;
  fields?: FormField[];
}

export const formFieldRequestSchema: Schema<FormFieldRequest> = object({
  field: ['field', optional(lazy(() => formFieldSchema))],
  fields: ['fields', optional(array(lazy(() => formFieldSchema)))],
});
