/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { FormStep, formStepSchema } from './formStep';
import { FormTypeEnum, formTypeEnumSchema } from './formTypeEnum';

export interface Form {
  data?: Record<string, unknown>;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  name?: string;
  steps?: FormStep[];
  type?: FormTypeEnum;
}

export const formSchema: Schema<Form> = object({
  data: ['data', optional(dict(unknown()))],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
  name: ['name', optional(string())],
  steps: ['steps', optional(array(lazy(() => formStepSchema)))],
  type: ['type', optional(formTypeEnumSchema)],
});
