/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FormControlEnum
 */
export enum FormControlEnum {
  Checkbox = 'checkbox',
  Number = 'number',
  Password = 'password',
  Radio = 'radio',
  Select = 'select',
  Textarea = 'textarea',
  Text = 'text',
}

/**
 * Schema for FormControlEnum
 */
export const  formControlEnumSchema: Schema<FormControlEnum> = stringEnum(FormControlEnum);
