/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface FormStep {
  fields?: string[];
}

export const formStepSchema: Schema<FormStep> = object({
  fields: ['fields', optional(array(string()))],
});
