/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Form, formSchema } from './form';

/** Form response. */
export interface FormRequest {
  form?: Form;
}

export const formRequestSchema: Schema<FormRequest> = object({
  form: ['form', optional(lazy(() => formSchema))],
});
