/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Google social login provider parameters. */
export interface GoogleIdentityProviderProperties {
  api?: string;
  button?: string;
}

export const googleIdentityProviderPropertiesSchema: Schema<GoogleIdentityProviderProperties> = object(
  { api: ['api', optional(string())], button: ['button', optional(string())] }
);
