/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { ApplicationRole, applicationRoleSchema } from './applicationRole';

export interface Group {
  data?: Record<string, unknown>;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  name?: string;
  roles?: ApplicationRole[];
  tenantId?: string;
}

export const groupSchema: Schema<Group> = object({
  data: ['data', optional(dict(unknown()))],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
  name: ['name', optional(string())],
  roles: ['roles', optional(array(lazy(() => applicationRoleSchema)))],
  tenantId: ['tenantId', optional(string())],
});
