/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  GroupSearchCriteria,
  groupSearchCriteriaSchema,
} from './groupSearchCriteria';

/** Search request for Groups. */
export interface GroupSearchRequest {
  /** Search criteria for Groups */
  search?: GroupSearchCriteria;
}

export const groupSearchRequestSchema: Schema<GroupSearchRequest> = object({
  search: ['search', optional(lazy(() => groupSearchCriteriaSchema))],
});
