/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Group, groupSchema } from './group';

/** Group API request object. */
export interface GroupRequest {
  group?: Group;
  roleIds?: string[];
}

export const groupRequestSchema: Schema<GroupRequest> = object({
  group: ['group', optional(lazy(() => groupSchema))],
  roleIds: ['roleIds', optional(array(string()))],
});
