/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Group, groupSchema } from './group';

/** Group API response object. */
export interface GroupResponse {
  group?: Group;
  groups?: Group[];
}

export const groupResponseSchema: Schema<GroupResponse> = object({
  group: ['group', optional(lazy(() => groupSchema))],
  groups: ['groups', optional(array(lazy(() => groupSchema)))],
});
