/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';
import { EventTypeEnum, eventTypeEnumSchema } from './eventTypeEnum';
import { Group, groupSchema } from './group';
import { GroupMember, groupMemberSchema } from './groupMember';

/** Models the Group Member Update Event. */
export interface GroupMemberUpdateEvent {
  group?: Group;
  members?: GroupMember[];
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  createInstant?: bigint;
  id?: string;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  info?: EventInfo;
  tenantId?: string;
  /** Models the event types that FusionAuth produces. */
  type?: EventTypeEnum;
}

export const groupMemberUpdateEventSchema: Schema<GroupMemberUpdateEvent> = object(
  {
    group: ['group', optional(lazy(() => groupSchema))],
    members: ['members', optional(array(lazy(() => groupMemberSchema)))],
    createInstant: ['createInstant', optional(bigint())],
    id: ['id', optional(string())],
    info: ['info', optional(lazy(() => eventInfoSchema))],
    tenantId: ['tenantId', optional(string())],
    type: ['type', optional(eventTypeEnumSchema)],
  }
);
