/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { GroupMember, groupMemberSchema } from './groupMember';

/** Search response for Group Members */
export interface GroupMemberSearchResponse {
  members?: GroupMember[];
  total?: bigint;
}

export const groupMemberSearchResponseSchema: Schema<GroupMemberSearchResponse> = object(
  {
    members: ['members', optional(array(lazy(() => groupMemberSchema)))],
    total: ['total', optional(bigint())],
  }
);
