/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { Group, groupSchema } from './group';

/** Search response for Groups */
export interface GroupSearchResponse {
  groups?: Group[];
  total?: bigint;
}

export const groupSearchResponseSchema: Schema<GroupSearchResponse> = object({
  groups: ['groups', optional(array(lazy(() => groupSchema)))],
  total: ['total', optional(bigint())],
});
