/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  GroupMemberSearchCriteria,
  groupMemberSearchCriteriaSchema,
} from './groupMemberSearchCriteria';

/** Search request for Group Members. */
export interface GroupMemberSearchRequest {
  /** Search criteria for Group Members */
  search?: GroupMemberSearchCriteria;
}

export const groupMemberSearchRequestSchema: Schema<GroupMemberSearchRequest> = object(
  { search: ['search', optional(lazy(() => groupMemberSearchCriteriaSchema))] }
);
