/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HTTPMethodEnum
 */
export enum HTTPMethodEnum {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS',
  PATCH = 'PATCH',
}

/**
 * Schema for HTTPMethodEnum
 */
export const  hTTPMethodEnumSchema: Schema<HTTPMethodEnum> = stringEnum(HTTPMethodEnum);
