/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ClientAuthenticationMethodEnum,
  clientAuthenticationMethodEnumSchema,
} from './clientAuthenticationMethodEnum';

export interface IdentityProviderOauth2Configuration {
  authorizationEndpoint?: string;
  clientAuthenticationMethod?: ClientAuthenticationMethodEnum;
  clientId?: string;
  clientSecret?: string;
  emailClaim?: string;
  emailVerifiedClaim?: string;
  issuer?: string;
  scope?: string;
  tokenEndpoint?: string;
  uniqueIdClaim?: string;
  userinfoEndpoint?: string;
  usernameClaim?: string;
}

export const identityProviderOauth2ConfigurationSchema: Schema<IdentityProviderOauth2Configuration> = object(
  {
    authorizationEndpoint: ['authorization_endpoint', optional(string())],
    clientAuthenticationMethod: [
      'clientAuthenticationMethod',
      optional(clientAuthenticationMethodEnumSchema),
    ],
    clientId: ['client_id', optional(string())],
    clientSecret: ['client_secret', optional(string())],
    emailClaim: ['emailClaim', optional(string())],
    emailVerifiedClaim: ['emailVerifiedClaim', optional(string())],
    issuer: ['issuer', optional(string())],
    scope: ['scope', optional(string())],
    tokenEndpoint: ['token_endpoint', optional(string())],
    uniqueIdClaim: ['uniqueIdClaim', optional(string())],
    userinfoEndpoint: ['userinfo_endpoint', optional(string())],
    usernameClaim: ['usernameClaim', optional(string())],
  }
);
