/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IdentityProviderTypeEnum
 */
export enum IdentityProviderTypeEnum {
  Apple = 'Apple',
  EpicGames = 'EpicGames',
  ExternalJWT = 'ExternalJWT',
  Facebook = 'Facebook',
  Google = 'Google',
  HYPR = 'HYPR',
  LinkedIn = 'LinkedIn',
  Nintendo = 'Nintendo',
  OpenIDConnect = 'OpenIDConnect',
  SAMLv2 = 'SAMLv2',
  SAMLv2IdPInitiated = 'SAMLv2IdPInitiated',
  SonyPSN = 'SonyPSN',
  Steam = 'Steam',
  Twitch = 'Twitch',
  Twitter = 'Twitter',
  Xbox = 'Xbox',
}

/**
 * Schema for IdentityProviderTypeEnum
 */
export const  identityProviderTypeEnumSchema: Schema<IdentityProviderTypeEnum> = stringEnum(IdentityProviderTypeEnum);
