/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  IdentityProviderLink,
  identityProviderLinkSchema,
} from './identityProviderLink';

export interface IdentityProviderLinkResponse {
  identityProviderLink?: IdentityProviderLink;
  identityProviderLinks?: IdentityProviderLink[];
}

export const identityProviderLinkResponseSchema: Schema<IdentityProviderLinkResponse> = object(
  {
    identityProviderLink: [
      'identityProviderLink',
      optional(lazy(() => identityProviderLinkSchema)),
    ],
    identityProviderLinks: [
      'identityProviderLinks',
      optional(array(lazy(() => identityProviderLinkSchema))),
    ],
  }
);
