/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { MetaData, metaDataSchema } from './metaData';

export interface IdentityProviderStartLoginRequest {
  data?: Record<string, string>;
  identityProviderId?: string;
  loginId?: string;
  state?: Record<string, unknown>;
  applicationId?: string;
  ipAddress?: string;
  metaData?: MetaData;
  newDevice?: boolean;
  noJWT?: boolean;
}

export const identityProviderStartLoginRequestSchema: Schema<IdentityProviderStartLoginRequest> = object(
  {
    data: ['data', optional(dict(string()))],
    identityProviderId: ['identityProviderId', optional(string())],
    loginId: ['loginId', optional(string())],
    state: ['state', optional(dict(unknown()))],
    applicationId: ['applicationId', optional(string())],
    ipAddress: ['ipAddress', optional(string())],
    metaData: ['metaData', optional(lazy(() => metaDataSchema))],
    newDevice: ['newDevice', optional(boolean())],
    noJWT: ['noJWT', optional(boolean())],
  }
);
