/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema, unknown } from '../schema';
import {
  IdentityProviderLimitUserLinkingPolicy,
  identityProviderLimitUserLinkingPolicySchema,
} from './identityProviderLimitUserLinkingPolicy';

export interface IdentityProviderTenantConfiguration {
  data?: Record<string, unknown>;
  limitUserLinkCount?: IdentityProviderLimitUserLinkingPolicy;
}

export const identityProviderTenantConfigurationSchema: Schema<IdentityProviderTenantConfiguration> = object(
  {
    data: ['data', optional(dict(unknown()))],
    limitUserLinkCount: [
      'limitUserLinkCount',
      optional(lazy(() => identityProviderLimitUserLinkingPolicySchema)),
    ],
  }
);
