/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  dict,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import {
  IdentityProviderTypeEnum,
  identityProviderTypeEnumSchema,
} from './identityProviderTypeEnum';

export interface IdentityProviderLink {
  data?: Record<string, unknown>;
  displayName?: string;
  identityProviderId?: string;
  identityProviderName?: string;
  identityProviderType?: IdentityProviderTypeEnum;
  identityProviderUserId?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastLoginInstant?: bigint;
  tenantId?: string;
  token?: string;
  userId?: string;
}

export const identityProviderLinkSchema: Schema<IdentityProviderLink> = object({
  data: ['data', optional(dict(unknown()))],
  displayName: ['displayName', optional(string())],
  identityProviderId: ['identityProviderId', optional(string())],
  identityProviderName: ['identityProviderName', optional(string())],
  identityProviderType: [
    'identityProviderType',
    optional(identityProviderTypeEnumSchema),
  ],
  identityProviderUserId: ['identityProviderUserId', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  lastLoginInstant: ['lastLoginInstant', optional(bigint())],
  tenantId: ['tenantId', optional(string())],
  token: ['token', optional(string())],
  userId: ['userId', optional(string())],
});
