/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  IdentityProviderField,
  identityProviderFieldSchema,
} from './containers/identityProviderField';

export interface IdentityProviderResponse {
  identityProvider?: IdentityProviderField;
  identityProviders?: IdentityProviderField[];
}

export const identityProviderResponseSchema: Schema<IdentityProviderResponse> = object(
  {
    identityProvider: [
      'identityProvider',
      optional(identityProviderFieldSchema),
    ],
    identityProviders: [
      'identityProviders',
      optional(array(identityProviderFieldSchema)),
    ],
  }
);
