/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  IdentityProviderField,
  identityProviderFieldSchema,
} from './containers/identityProviderField';

export interface IdentityProviderRequest {
  identityProvider?: IdentityProviderField;
}

export const identityProviderRequestSchema: Schema<IdentityProviderRequest> = object(
  {
    identityProvider: [
      'identityProvider',
      optional(identityProviderFieldSchema),
    ],
  }
);
