/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IPAccessControlEntryActionEnum
 */
export enum IPAccessControlEntryActionEnum {
  Allow = 'Allow',
  Block = 'Block',
}

/**
 * Schema for IPAccessControlEntryActionEnum
 */
export const  iPAccessControlEntryActionEnumSchema: Schema<IPAccessControlEntryActionEnum> = stringEnum(IPAccessControlEntryActionEnum);
