/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { AlgorithmEnum, algorithmEnumSchema } from './algorithmEnum';
import { KeyTypeEnum, keyTypeEnumSchema } from './keyTypeEnum';

/** A JSON Web Key as defined by <a href="https:tools.ietf.orghtmlrfc7517#section-4">RFC 7517 JSON Web Key (JWK)  Section 4<a> and <a href="https:tools.ietf.orghtmlrfc7518">RFC 7518 JSON Web Algorithms (JWA)<a>. */
export interface JSONWebKey {
  /** Available JSON Web Algorithms (JWA) as described in RFC 7518 available for this JWT implementation. */
  alg?: AlgorithmEnum;
  crv?: string;
  d?: string;
  dp?: string;
  dq?: string;
  e?: string;
  kid?: string;
  kty?: KeyTypeEnum;
  n?: string;
  other?: Record<string, unknown>;
  p?: string;
  q?: string;
  qi?: string;
  use?: string;
  x?: string;
  x5c?: string[];
  x5t?: string;
  x5tS256?: string;
  y?: string;
}

export const jSONWebKeySchema: Schema<JSONWebKey> = object({
  alg: ['alg', optional(algorithmEnumSchema)],
  crv: ['crv', optional(string())],
  d: ['d', optional(string())],
  dp: ['dp', optional(string())],
  dq: ['dq', optional(string())],
  e: ['e', optional(string())],
  kid: ['kid', optional(string())],
  kty: ['kty', optional(keyTypeEnumSchema)],
  n: ['n', optional(string())],
  other: ['other', optional(dict(unknown()))],
  p: ['p', optional(string())],
  q: ['q', optional(string())],
  qi: ['qi', optional(string())],
  use: ['use', optional(string())],
  x: ['x', optional(string())],
  x5c: ['x5c', optional(array(string()))],
  x5t: ['x5t', optional(string())],
  x5tS256: ['x5t#S256', optional(string())],
  y: ['y', optional(string())],
});
