/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { JSONWebKey, jSONWebKeySchema } from './jSONWebKey';

export interface JWKSResponse {
  keys?: JSONWebKey[];
}

export const jWKSResponseSchema: Schema<JWKSResponse> = object({
  keys: ['keys', optional(array(lazy(() => jSONWebKeySchema)))],
});
