/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';
import { EventTypeEnum, eventTypeEnumSchema } from './eventTypeEnum';
import { RefreshToken, refreshTokenSchema } from './refreshToken';
import { User, userSchema } from './user';

/** Models the Refresh Token Revoke Event. This event might be for a single token, a user  or an entire application. */
export interface JWTRefreshTokenRevokeEvent {
  applicationId?: string;
  applicationTimeToLiveInSeconds?: Record<string, number>;
  /** Models a JWT Refresh Token. */
  refreshToken?: RefreshToken;
  /** The global view of a User. This object contains all global information about the user including birthdate, registration information  preferred languages, global attributes, etc. */
  user?: User;
  userId?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  createInstant?: bigint;
  id?: string;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  info?: EventInfo;
  tenantId?: string;
  /** Models the event types that FusionAuth produces. */
  type?: EventTypeEnum;
}

export const jWTRefreshTokenRevokeEventSchema: Schema<JWTRefreshTokenRevokeEvent> = object(
  {
    applicationId: ['applicationId', optional(string())],
    applicationTimeToLiveInSeconds: [
      'applicationTimeToLiveInSeconds',
      optional(dict(number())),
    ],
    refreshToken: ['refreshToken', optional(lazy(() => refreshTokenSchema))],
    user: ['user', optional(lazy(() => userSchema))],
    userId: ['userId', optional(string())],
    createInstant: ['createInstant', optional(bigint())],
    id: ['id', optional(string())],
    info: ['info', optional(lazy(() => eventInfoSchema))],
    tenantId: ['tenantId', optional(string())],
    type: ['type', optional(eventTypeEnumSchema)],
  }
);
