/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { KeyAlgorithmEnum, keyAlgorithmEnumSchema } from './keyAlgorithmEnum';
import { KeyTypeEnum, keyTypeEnumSchema } from './keyTypeEnum';

/** Search criteria for Keys */
export interface KeySearchCriteria {
  algorithm?: KeyAlgorithmEnum;
  name?: string;
  type?: KeyTypeEnum;
  numberOfResults?: number;
  orderBy?: string;
  startRow?: number;
}

export const keySearchCriteriaSchema: Schema<KeySearchCriteria> = object({
  algorithm: ['algorithm', optional(keyAlgorithmEnumSchema)],
  name: ['name', optional(string())],
  type: ['type', optional(keyTypeEnumSchema)],
  numberOfResults: ['numberOfResults', optional(number())],
  orderBy: ['orderBy', optional(string())],
  startRow: ['startRow', optional(number())],
});
