/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for KeyUseEnum
 */
export enum KeyUseEnum {
  SignOnly = 'SignOnly',
  SignAndVerify = 'SignAndVerify',
  VerifyOnly = 'VerifyOnly',
}

/**
 * Schema for KeyUseEnum
 */
export const  keyUseEnumSchema: Schema<KeyUseEnum> = stringEnum(KeyUseEnum);
