/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  LambdaSearchCriteria,
  lambdaSearchCriteriaSchema,
} from './lambdaSearchCriteria';

/** Search request for Lambdas */
export interface LambdaSearchRequest {
  /** Search criteria for Lambdas */
  search?: LambdaSearchCriteria;
}

export const lambdaSearchRequestSchema: Schema<LambdaSearchRequest> = object({
  search: ['search', optional(lazy(() => lambdaSearchCriteriaSchema))],
});
