/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { LambdaTypeEnum, lambdaTypeEnumSchema } from './lambdaTypeEnum';

/** Search criteria for Lambdas */
export interface LambdaSearchCriteria {
  body?: string;
  name?: string;
  /** The types of lambdas that indicate how they are invoked by FusionAuth. */
  type?: LambdaTypeEnum;
  numberOfResults?: number;
  orderBy?: string;
  startRow?: number;
}

export const lambdaSearchCriteriaSchema: Schema<LambdaSearchCriteria> = object({
  body: ['body', optional(string())],
  name: ['name', optional(string())],
  type: ['type', optional(lambdaTypeEnumSchema)],
  numberOfResults: ['numberOfResults', optional(number())],
  orderBy: ['orderBy', optional(string())],
  startRow: ['startRow', optional(number())],
});
