/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LambdaConfiguration {
  accessTokenPopulateId?: string;
  idTokenPopulateId?: string;
  samlv2PopulateId?: string;
  selfServiceRegistrationValidationId?: string;
  userinfoPopulateId?: string;
}

export const lambdaConfigurationSchema: Schema<LambdaConfiguration> = object({
  accessTokenPopulateId: ['accessTokenPopulateId', optional(string())],
  idTokenPopulateId: ['idTokenPopulateId', optional(string())],
  samlv2PopulateId: ['samlv2PopulateId', optional(string())],
  selfServiceRegistrationValidationId: [
    'selfServiceRegistrationValidationId',
    optional(string()),
  ],
  userinfoPopulateId: ['userinfoPopulateId', optional(string())],
});
