/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, boolean, object, optional, Schema, string } from '../schema';
import {
  LambdaEngineTypeEnum,
  lambdaEngineTypeEnumSchema,
} from './lambdaEngineTypeEnum';
import { LambdaTypeEnum, lambdaTypeEnumSchema } from './lambdaTypeEnum';

/** A JavaScript lambda function that is executed during certain events inside FusionAuth. */
export interface Lambda {
  body?: string;
  debug?: boolean;
  engineType?: LambdaEngineTypeEnum;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  name?: string;
  /** The types of lambdas that indicate how they are invoked by FusionAuth. */
  type?: LambdaTypeEnum;
}

export const lambdaSchema: Schema<Lambda> = object({
  body: ['body', optional(string())],
  debug: ['debug', optional(boolean())],
  engineType: ['engineType', optional(lambdaEngineTypeEnumSchema)],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
  name: ['name', optional(string())],
  type: ['type', optional(lambdaTypeEnumSchema)],
});
