/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Lambda, lambdaSchema } from './lambda';

/** Lambda API response object. */
export interface LambdaResponse {
  /** A JavaScript lambda function that is executed during certain events inside FusionAuth. */
  lambda?: Lambda;
  lambdas?: Lambda[];
}

export const lambdaResponseSchema: Schema<LambdaResponse> = object({
  lambda: ['lambda', optional(lazy(() => lambdaSchema))],
  lambdas: ['lambdas', optional(array(lazy(() => lambdaSchema)))],
});
