/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import {
  ConnectorLambdaConfiguration,
  connectorLambdaConfigurationSchema,
} from './connectorLambdaConfiguration';
import { ConnectorTypeEnum, connectorTypeEnumSchema } from './connectorTypeEnum';
import {
  LDAPSecurityMethodEnum,
  lDAPSecurityMethodEnumSchema,
} from './lDAPSecurityMethodEnum';

/** Models an LDAP connector. */
export interface LDAPConnectorConfiguration {
  authenticationURL?: string;
  baseStructure?: string;
  connectTimeout?: number;
  identifyingAttribute?: string;
  lambdaConfiguration?: ConnectorLambdaConfiguration;
  loginIdAttribute?: string;
  readTimeout?: number;
  requestedAttributes?: string[];
  securityMethod?: LDAPSecurityMethodEnum;
  systemAccountDN?: string;
  systemAccountPassword?: string;
  data?: Record<string, unknown>;
  debug?: boolean;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  lastUpdateInstant?: bigint;
  name?: string;
  /** The types of connectors. This enum is stored as an ordinal on the <code>identities<code> table, order must be maintained. */
  type?: ConnectorTypeEnum;
}

export const lDAPConnectorConfigurationSchema: Schema<LDAPConnectorConfiguration> = object(
  {
    authenticationURL: ['authenticationURL', optional(string())],
    baseStructure: ['baseStructure', optional(string())],
    connectTimeout: ['connectTimeout', optional(number())],
    identifyingAttribute: ['identifyingAttribute', optional(string())],
    lambdaConfiguration: [
      'lambdaConfiguration',
      optional(lazy(() => connectorLambdaConfigurationSchema)),
    ],
    loginIdAttribute: ['loginIdAttribute', optional(string())],
    readTimeout: ['readTimeout', optional(number())],
    requestedAttributes: ['requestedAttributes', optional(array(string()))],
    securityMethod: ['securityMethod', optional(lDAPSecurityMethodEnumSchema)],
    systemAccountDN: ['systemAccountDN', optional(string())],
    systemAccountPassword: ['systemAccountPassword', optional(string())],
    data: ['data', optional(dict(unknown()))],
    debug: ['debug', optional(boolean())],
    id: ['id', optional(string())],
    insertInstant: ['insertInstant', optional(bigint())],
    lastUpdateInstant: ['lastUpdateInstant', optional(bigint())],
    name: ['name', optional(string())],
    type: ['type', optional(connectorTypeEnumSchema)],
  }
);
