/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Location information. Useful for IP addresses and other displayable data objects. */
export interface Location {
  city?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
  region?: string;
  zipcode?: string;
  displayString?: string;
}

export const locationSchema: Schema<Location> = object({
  city: ['city', optional(string())],
  country: ['country', optional(string())],
  latitude: ['latitude', optional(number())],
  longitude: ['longitude', optional(number())],
  region: ['region', optional(string())],
  zipcode: ['zipcode', optional(string())],
  displayString: ['displayString', optional(string())],
});
