/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { HistoryItem, historyItemSchema } from './historyItem';

/** A historical state of a user log event. Since events can be modified, this stores the historical state. */
export interface LogHistory {
  historyItems?: HistoryItem[];
}

export const logHistorySchema: Schema<LogHistory> = object({
  historyItems: [
    'historyItems',
    optional(array(lazy(() => historyItemSchema))),
  ],
});
