/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import { MetaData, metaDataSchema } from './metaData';

/** Login Ping API request object. */
export interface LoginPingRequest {
  userId?: string;
  applicationId?: string;
  ipAddress?: string;
  metaData?: MetaData;
  newDevice?: boolean;
  noJWT?: boolean;
}

export const loginPingRequestSchema: Schema<LoginPingRequest> = object({
  userId: ['userId', optional(string())],
  applicationId: ['applicationId', optional(string())],
  ipAddress: ['ipAddress', optional(string())],
  metaData: ['metaData', optional(lazy(() => metaDataSchema))],
  newDevice: ['newDevice', optional(boolean())],
  noJWT: ['noJWT', optional(boolean())],
});
