/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  LoginRecordSearchCriteria,
  loginRecordSearchCriteriaSchema,
} from './loginRecordSearchCriteria';

export interface LoginRecordExportRequest {
  criteria?: LoginRecordSearchCriteria;
  dateTimeSecondsFormat?: string;
  /** Timezone Identifier */
  zoneId?: string;
}

export const loginRecordExportRequestSchema: Schema<LoginRecordExportRequest> = object(
  {
    criteria: [
      'criteria',
      optional(lazy(() => loginRecordSearchCriteriaSchema)),
    ],
    dateTimeSecondsFormat: ['dateTimeSecondsFormat', optional(string())],
    zoneId: ['zoneId', optional(string())],
  }
);
