/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface LoginRecordSearchCriteria {
  applicationId?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  end?: bigint;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  start?: bigint;
  userId?: string;
  numberOfResults?: number;
  orderBy?: string;
  startRow?: number;
}

export const loginRecordSearchCriteriaSchema: Schema<LoginRecordSearchCriteria> = object(
  {
    applicationId: ['applicationId', optional(string())],
    end: ['end', optional(bigint())],
    start: ['start', optional(bigint())],
    userId: ['userId', optional(string())],
    numberOfResults: ['numberOfResults', optional(number())],
    orderBy: ['orderBy', optional(string())],
    startRow: ['startRow', optional(number())],
  }
);
