/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface LoginConfiguration {
  allowTokenRefresh?: boolean;
  generateRefreshTokens?: boolean;
  requireAuthentication?: boolean;
}

export const loginConfigurationSchema: Schema<LoginConfiguration> = object({
  allowTokenRefresh: ['allowTokenRefresh', optional(boolean())],
  generateRefreshTokens: ['generateRefreshTokens', optional(boolean())],
  requireAuthentication: ['requireAuthentication', optional(boolean())],
});
