/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { Count, countSchema } from './count';

/** Response for the login report. */
export interface LoginReportResponse {
  hourlyCounts?: Count[];
  total?: bigint;
}

export const loginReportResponseSchema: Schema<LoginReportResponse> = object({
  hourlyCounts: ['hourlyCounts', optional(array(lazy(() => countSchema)))],
  total: ['total', optional(bigint())],
});
