/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import { MetaData, metaDataSchema } from './metaData';

/** Login API request object. */
export interface LoginRequest {
  loginId?: string;
  oneTimePassword?: string;
  password?: string;
  twoFactorTrustId?: string;
  applicationId?: string;
  ipAddress?: string;
  metaData?: MetaData;
  newDevice?: boolean;
  noJWT?: boolean;
}

export const loginRequestSchema: Schema<LoginRequest> = object({
  loginId: ['loginId', optional(string())],
  oneTimePassword: ['oneTimePassword', optional(string())],
  password: ['password', optional(string())],
  twoFactorTrustId: ['twoFactorTrustId', optional(string())],
  applicationId: ['applicationId', optional(string())],
  ipAddress: ['ipAddress', optional(string())],
  metaData: ['metaData', optional(lazy(() => metaDataSchema))],
  newDevice: ['newDevice', optional(boolean())],
  noJWT: ['noJWT', optional(boolean())],
});
