/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

/** The summary of the action that is preventing login to be returned on the login response. */
export interface LoginPreventedResponse {
  actionId?: string;
  actionerUserId?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  expiry?: bigint;
  localizedName?: string;
  localizedOption?: string;
  localizedReason?: string;
  name?: string;
  option?: string;
  reason?: string;
  reasonCode?: string;
}

export const loginPreventedResponseSchema: Schema<LoginPreventedResponse> = object(
  {
    actionId: ['actionId', optional(string())],
    actionerUserId: ['actionerUserId', optional(string())],
    expiry: ['expiry', optional(bigint())],
    localizedName: ['localizedName', optional(string())],
    localizedOption: ['localizedOption', optional(string())],
    localizedReason: ['localizedReason', optional(string())],
    name: ['name', optional(string())],
    option: ['option', optional(string())],
    reason: ['reason', optional(string())],
    reasonCode: ['reasonCode', optional(string())],
  }
);
