/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface MaximumPasswordAge {
  days?: number;
  enabled?: boolean;
}

export const maximumPasswordAgeSchema: Schema<MaximumPasswordAge> = object({
  days: ['days', optional(number())],
  enabled: ['enabled', optional(boolean())],
});
