/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { GroupMember, groupMemberSchema } from './groupMember';

/** Group Member Response */
export interface MemberResponse {
  members?: GroupMember[];
}

export const memberResponseSchema: Schema<MemberResponse> = object({
  members: ['members', optional(array(lazy(() => groupMemberSchema)))],
});
