/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MessageTypeEnum
 */
export enum MessageTypeEnum {
  SMS = 'SMS',
}

/**
 * Schema for MessageTypeEnum
 */
export const  messageTypeEnumSchema: Schema<MessageTypeEnum> = stringEnum(MessageTypeEnum);
