/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MessengerTypeEnum
 */
export enum MessengerTypeEnum {
  Generic = 'Generic',
  Kafka = 'Kafka',
  Twilio = 'Twilio',
}

/**
 * Schema for MessengerTypeEnum
 */
export const  messengerTypeEnumSchema: Schema<MessengerTypeEnum> = stringEnum(MessengerTypeEnum);
