/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { Count, countSchema } from './count';

/** Response for the daily active user report. */
export interface MonthlyActiveUserReportResponse {
  monthlyActiveUsers?: Count[];
  total?: bigint;
}

export const monthlyActiveUserReportResponseSchema: Schema<MonthlyActiveUserReportResponse> = object(
  {
    monthlyActiveUsers: [
      'monthlyActiveUsers',
      optional(array(lazy(() => countSchema))),
    ],
    total: ['total', optional(bigint())],
  }
);
