/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface MultiFactorEmailMethod {
  templateId?: string;
  enabled?: boolean;
}

export const multiFactorEmailMethodSchema: Schema<MultiFactorEmailMethod> = object(
  {
    templateId: ['templateId', optional(string())],
    enabled: ['enabled', optional(boolean())],
  }
);
