/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthErrorTypeEnum
 */
export enum OAuthErrorTypeEnum {
  InvalidRequest = 'invalid_request',
  InvalidClient = 'invalid_client',
  InvalidGrant = 'invalid_grant',
  InvalidToken = 'invalid_token',
  UnauthorizedClient = 'unauthorized_client',
  InvalidScope = 'invalid_scope',
  ServerError = 'server_error',
  UnsupportedGrantType = 'unsupported_grant_type',
  UnsupportedResponseType = 'unsupported_response_type',
  AccessDenied = 'access_denied',
  ChangePasswordRequired = 'change_password_required',
  NotLicensed = 'not_licensed',
  TwoFactorRequired = 'two_factor_required',
  AuthorizationPending = 'authorization_pending',
  ExpiredToken = 'expired_token',
  UnsupportedTokenType = 'unsupported_token_type',
}

/**
 * Schema for OAuthErrorTypeEnum
 */
export const  oAuthErrorTypeEnumSchema: Schema<OAuthErrorTypeEnum> = stringEnum(OAuthErrorTypeEnum);
