/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthScopeConsentModeEnum
 */
export enum OAuthScopeConsentModeEnum {
  AlwaysPrompt = 'AlwaysPrompt',
  RememberDecision = 'RememberDecision',
  NeverPrompt = 'NeverPrompt',
}

/**
 * Schema for OAuthScopeConsentModeEnum
 */
export const  oAuthScopeConsentModeEnumSchema: Schema<OAuthScopeConsentModeEnum> = stringEnum(OAuthScopeConsentModeEnum);
