/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthApplicationRelationshipEnum
 */
export enum OAuthApplicationRelationshipEnum {
  FirstParty = 'FirstParty',
  ThirdParty = 'ThirdParty',
}

/**
 * Schema for OAuthApplicationRelationshipEnum
 */
export const  oAuthApplicationRelationshipEnumSchema: Schema<OAuthApplicationRelationshipEnum> = stringEnum(OAuthApplicationRelationshipEnum);
