/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string, unknown } from '../schema';

export interface PasswordlessStartRequest {
  applicationId?: string;
  loginId?: string;
  state?: Record<string, unknown>;
}

export const passwordlessStartRequestSchema: Schema<PasswordlessStartRequest> = object(
  {
    applicationId: ['applicationId', optional(string())],
    loginId: ['loginId', optional(string())],
    state: ['state', optional(dict(unknown()))],
  }
);
