/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { User, userSchema } from './user';

export interface PendingResponse {
  users?: User[];
}

export const pendingResponseSchema: Schema<PendingResponse> = object({
  users: ['users', optional(array(lazy(() => userSchema)))],
});
