/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { MessageTemplate, messageTemplateSchema } from './messageTemplate';

export interface PreviewMessageTemplateRequest {
  /** A Locale object represents a specific geographical, political, or cultural region. */
  locale?: string;
  /** Stores an message template used to distribute messages; */
  messageTemplate?: MessageTemplate;
}

export const previewMessageTemplateRequestSchema: Schema<PreviewMessageTemplateRequest> = object(
  {
    locale: ['locale', optional(string())],
    messageTemplate: [
      'messageTemplate',
      optional(lazy(() => messageTemplateSchema)),
    ],
  }
);
