/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProofKeyForCodeExchangePolicyEnum
 */
export enum ProofKeyForCodeExchangePolicyEnum {
  Required = 'Required',
  NotRequired = 'NotRequired',
  NotRequiredWhenUsingClientAuthentication = 'NotRequiredWhenUsingClientAuthentication',
}

/**
 * Schema for ProofKeyForCodeExchangePolicyEnum
 */
export const  proofKeyForCodeExchangePolicyEnumSchema: Schema<ProofKeyForCodeExchangePolicyEnum> = stringEnum(ProofKeyForCodeExchangePolicyEnum);
