/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ProviderLambdaConfiguration {
  reconcileId?: string;
}

export const providerLambdaConfigurationSchema: Schema<ProviderLambdaConfiguration> = object(
  { reconcileId: ['reconcileId', optional(string())] }
);
