/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Supply additional information about the Relying Party when creating a new credential */
export interface PublicKeyCredentialRelyingPartyEntity {
  id?: string;
  name?: string;
}

export const publicKeyCredentialRelyingPartyEntitySchema: Schema<PublicKeyCredentialRelyingPartyEntity> = object(
  { id: ['id', optional(string())], name: ['name', optional(string())] }
);
