/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Supply additional information about the user account when creating a new credential */
export interface PublicKeyCredentialUserEntity {
  displayName?: string;
  id?: string;
  name?: string;
}

export const publicKeyCredentialUserEntitySchema: Schema<PublicKeyCredentialUserEntity> = object(
  {
    displayName: ['displayName', optional(string())],
    id: ['id', optional(string())],
    name: ['name', optional(string())],
  }
);
