/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Describes a user account or WebAuthn Relying Party associated with a public key credential */
export interface PublicKeyCredentialEntity {
  name?: string;
}

export const publicKeyCredentialEntitySchema: Schema<PublicKeyCredentialEntity> = object(
  { name: ['name', optional(string())] }
);
