/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CoseAlgorithmIdentifierEnum,
  coseAlgorithmIdentifierEnumSchema,
} from './coseAlgorithmIdentifierEnum';
import {
  PublicKeyCredentialTypeEnum,
  publicKeyCredentialTypeEnumSchema,
} from './publicKeyCredentialTypeEnum';

/** Supply information on credential type and algorithm to the <i>authenticator<i>. */
export interface PublicKeyCredentialParameters {
  /** A number identifying a cryptographic algorithm. Values should be registered with the <a  href="https:www.iana.orgassignmentscosecose.xhtml#algorithms">IANA COSE Algorithms registry<a> */
  alg?: CoseAlgorithmIdentifierEnum;
  /** Defines valid credential types. This is an extension point in the WebAuthn spec. The only defined value at this time is "public-key" */
  type?: PublicKeyCredentialTypeEnum;
}

export const publicKeyCredentialParametersSchema: Schema<PublicKeyCredentialParameters> = object(
  {
    alg: ['alg', optional(coseAlgorithmIdentifierEnumSchema)],
    type: ['type', optional(publicKeyCredentialTypeEnumSchema)],
  }
);
