/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PublicKeyCredentialTypeEnum
 */
export enum PublicKeyCredentialTypeEnum {
  PublicKey = 'publicKey',
}

/**
 * Schema for PublicKeyCredentialTypeEnum
 */
export const  publicKeyCredentialTypeEnumSchema: Schema<PublicKeyCredentialTypeEnum> = stringEnum(PublicKeyCredentialTypeEnum);
