/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RateLimitedRequestTypeEnum
 */
export enum RateLimitedRequestTypeEnum {
  FailedLogin = 'FailedLogin',
  ForgotPassword = 'ForgotPassword',
  SendEmailVerification = 'SendEmailVerification',
  SendPasswordless = 'SendPasswordless',
  SendRegistrationVerification = 'SendRegistrationVerification',
  SendTwoFactor = 'SendTwoFactor',
}

/**
 * Schema for RateLimitedRequestTypeEnum
 */
export const  rateLimitedRequestTypeEnumSchema: Schema<RateLimitedRequestTypeEnum> = stringEnum(RateLimitedRequestTypeEnum);
