/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface RateLimitedRequestConfiguration {
  limit?: number;
  timePeriodInSeconds?: number;
  enabled?: boolean;
}

export const rateLimitedRequestConfigurationSchema: Schema<RateLimitedRequestConfiguration> = object(
  {
    limit: ['limit', optional(number())],
    timePeriodInSeconds: ['timePeriodInSeconds', optional(number())],
    enabled: ['enabled', optional(boolean())],
  }
);
