/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

/** Raw login information for each time a user logs into an application. */
export interface RawLogin {
  applicationId?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  instant?: bigint;
  ipAddress?: string;
  userId?: string;
}

export const rawLoginSchema: Schema<RawLogin> = object({
  applicationId: ['applicationId', optional(string())],
  instant: ['instant', optional(bigint())],
  ipAddress: ['ipAddress', optional(string())],
  userId: ['userId', optional(string())],
});
