/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ReactorMetrics, reactorMetricsSchema } from './reactorMetrics';

export interface ReactorMetricsResponse {
  metrics?: ReactorMetrics;
}

export const reactorMetricsResponseSchema: Schema<ReactorMetricsResponse> = object(
  { metrics: ['metrics', optional(lazy(() => reactorMetricsSchema))] }
);
