/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface RefreshTokenSlidingWindowConfiguration {
  maximumTimeToLiveInMinutes?: number;
}

export const refreshTokenSlidingWindowConfigurationSchema: Schema<RefreshTokenSlidingWindowConfiguration> = object(
  {
    maximumTimeToLiveInMinutes: [
      'maximumTimeToLiveInMinutes',
      optional(number()),
    ],
  }
);
