/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RefreshTokenExpirationPolicyEnum
 */
export enum RefreshTokenExpirationPolicyEnum {
  Fixed = 'Fixed',
  SlidingWindow = 'SlidingWindow',
  SlidingWindowWithMaximumLifetime = 'SlidingWindowWithMaximumLifetime',
}

/**
 * Schema for RefreshTokenExpirationPolicyEnum
 */
export const  refreshTokenExpirationPolicyEnumSchema: Schema<RefreshTokenExpirationPolicyEnum> = stringEnum(RefreshTokenExpirationPolicyEnum);
