/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { MetaData, metaDataSchema } from './metaData';

/** Models a JWT Refresh Token. */
export interface RefreshToken {
  applicationId?: string;
  data?: Record<string, unknown>;
  id?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  insertInstant?: bigint;
  metaData?: MetaData;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  startInstant?: bigint;
  tenantId?: string;
  token?: string;
  userId?: string;
}

export const refreshTokenSchema: Schema<RefreshToken> = object({
  applicationId: ['applicationId', optional(string())],
  data: ['data', optional(dict(unknown()))],
  id: ['id', optional(string())],
  insertInstant: ['insertInstant', optional(bigint())],
  metaData: ['metaData', optional(lazy(() => metaDataSchema))],
  startInstant: ['startInstant', optional(bigint())],
  tenantId: ['tenantId', optional(string())],
  token: ['token', optional(string())],
  userId: ['userId', optional(string())],
});
