/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';
import { User, userSchema } from './user';
import { UserRegistration, userRegistrationSchema } from './userRegistration';

/** Registration API request object. */
export interface RegistrationRequest {
  disableDomainBlock?: boolean;
  generateAuthenticationToken?: boolean;
  /** User registration information for a single application. */
  registration?: UserRegistration;
  sendSetPasswordEmail?: boolean;
  skipRegistrationVerification?: boolean;
  skipVerification?: boolean;
  /** The global view of a User. This object contains all global information about the user including birthdate, registration information  preferred languages, global attributes, etc. */
  user?: User;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const registrationRequestSchema: Schema<RegistrationRequest> = object({
  disableDomainBlock: ['disableDomainBlock', optional(boolean())],
  generateAuthenticationToken: [
    'generateAuthenticationToken',
    optional(boolean()),
  ],
  registration: ['registration', optional(lazy(() => userRegistrationSchema))],
  sendSetPasswordEmail: ['sendSetPasswordEmail', optional(boolean())],
  skipRegistrationVerification: [
    'skipRegistrationVerification',
    optional(boolean()),
  ],
  skipVerification: ['skipVerification', optional(boolean())],
  user: ['user', optional(lazy(() => userSchema))],
  eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))],
});
