/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { Count, countSchema } from './count';

/** Response for the registration report. */
export interface RegistrationReportResponse {
  hourlyCounts?: Count[];
  total?: bigint;
}

export const registrationReportResponseSchema: Schema<RegistrationReportResponse> = object(
  {
    hourlyCounts: ['hourlyCounts', optional(array(lazy(() => countSchema)))],
    total: ['total', optional(bigint())],
  }
);
