/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';

/** Registration delete API request object. */
export interface RegistrationDeleteRequest {
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const registrationDeleteRequestSchema: Schema<RegistrationDeleteRequest> = object(
  { eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))] }
);
