/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Reindex API request */
export interface ReindexRequest {
  index?: string;
}

export const reindexRequestSchema: Schema<ReindexRequest> = object({
  index: ['index', optional(string())],
});
