/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResidentKeyRequirementEnum
 */
export enum ResidentKeyRequirementEnum {
  Discouraged = 'discouraged',
  Preferred = 'preferred',
  Required = 'required',
}

/**
 * Schema for ResidentKeyRequirementEnum
 */
export const  residentKeyRequirementEnumSchema: Schema<ResidentKeyRequirementEnum> = stringEnum(ResidentKeyRequirementEnum);
