/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface SAMLv2AssertionEncryptionConfiguration {
  digestAlgorithm?: string;
  encryptionAlgorithm?: string;
  keyLocation?: string;
  keyTransportAlgorithm?: string;
  keyTransportEncryptionKeyId?: string;
  maskGenerationFunction?: string;
  enabled?: boolean;
}

export const sAMLv2AssertionEncryptionConfigurationSchema: Schema<SAMLv2AssertionEncryptionConfiguration> = object(
  {
    digestAlgorithm: ['digestAlgorithm', optional(string())],
    encryptionAlgorithm: ['encryptionAlgorithm', optional(string())],
    keyLocation: ['keyLocation', optional(string())],
    keyTransportAlgorithm: ['keyTransportAlgorithm', optional(string())],
    keyTransportEncryptionKeyId: [
      'keyTransportEncryptionKeyId',
      optional(string()),
    ],
    maskGenerationFunction: ['maskGenerationFunction', optional(string())],
    enabled: ['enabled', optional(boolean())],
  }
);
