/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

/** IdP Initiated login configuration */
export interface SAMLv2IdPInitiatedLoginConfiguration {
  nameIdFormat?: string;
  enabled?: boolean;
}

export const sAMLv2IdPInitiatedLoginConfigurationSchema: Schema<SAMLv2IdPInitiatedLoginConfiguration> = object(
  {
    nameIdFormat: ['nameIdFormat', optional(string())],
    enabled: ['enabled', optional(boolean())],
  }
);
