/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import {
  CanonicalizationMethodEnum,
  canonicalizationMethodEnumSchema,
} from './canonicalizationMethodEnum';

export interface SAMLv2SingleLogout {
  keyId?: string;
  url?: string;
  /** XML canonicalization method enumeration. This is used for the IdP and SP side of FusionAuth SAML. */
  xmlSignatureC14nMethod?: CanonicalizationMethodEnum;
  enabled?: boolean;
}

export const sAMLv2SingleLogoutSchema: Schema<SAMLv2SingleLogout> = object({
  keyId: ['keyId', optional(string())],
  url: ['url', optional(string())],
  xmlSignatureC14nMethod: [
    'xmlSignatureC14nMethod',
    optional(canonicalizationMethodEnumSchema),
  ],
  enabled: ['enabled', optional(boolean())],
});
