/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SAMLv2DestinationAssertionPolicyEnum
 */
export enum SAMLv2DestinationAssertionPolicyEnum {
  Enabled = 'Enabled',
  Disabled = 'Disabled',
  AllowAlternates = 'AllowAlternates',
}

/**
 * Schema for SAMLv2DestinationAssertionPolicyEnum
 */
export const  sAMLv2DestinationAssertionPolicyEnumSchema: Schema<SAMLv2DestinationAssertionPolicyEnum> = stringEnum(SAMLv2DestinationAssertionPolicyEnum);
