/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { User, userSchema } from './user';

/** Search API response. */
export interface SearchResponse {
  total?: bigint;
  nextResults?: string;
  users?: User[];
  expandable?: string[];
}

export const searchResponseSchema: Schema<SearchResponse> = object({
  total: ['total', optional(bigint())],
  nextResults: ['nextResults', optional(string())],
  users: ['users', optional(array(lazy(() => userSchema)))],
  expandable: ['expandable', optional(array(string()))],
});
