/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface SelfServiceFormConfiguration {
  requireCurrentPasswordOnPasswordChange?: boolean;
}

export const selfServiceFormConfigurationSchema: Schema<SelfServiceFormConfiguration> = object(
  {
    requireCurrentPasswordOnPasswordChange: [
      'requireCurrentPasswordOnPasswordChange',
      optional(boolean()),
    ],
  }
);
