/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema } from '../schema';
import {
  EmailTemplateErrors,
  emailTemplateErrorsSchema,
} from './emailTemplateErrors';

export interface SendResponse {
  anonymousResults?: Record<string, EmailTemplateErrors>;
  results?: Record<string, EmailTemplateErrors>;
}

export const sendResponseSchema: Schema<SendResponse> = object({
  anonymousResults: [
    'anonymousResults',
    optional(dict(lazy(() => emailTemplateErrorsSchema))),
  ],
  results: ['results', optional(dict(lazy(() => emailTemplateErrorsSchema)))],
});
