/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { EmailAddress, emailAddressSchema } from './emailAddress';

export interface SendRequest {
  applicationId?: string;
  bccAddresses?: string[];
  ccAddresses?: string[];
  preferredLanguages?: string[];
  requestData?: Record<string, unknown>;
  toAddresses?: EmailAddress[];
  userIds?: string[];
}

export const sendRequestSchema: Schema<SendRequest> = object({
  applicationId: ['applicationId', optional(string())],
  bccAddresses: ['bccAddresses', optional(array(string()))],
  ccAddresses: ['ccAddresses', optional(array(string()))],
  preferredLanguages: ['preferredLanguages', optional(array(string()))],
  requestData: ['requestData', optional(dict(unknown()))],
  toAddresses: ['toAddresses', optional(array(lazy(() => emailAddressSchema)))],
  userIds: ['userIds', optional(array(string()))],
});
