/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { SteamAPIModeEnum, steamAPIModeEnumSchema } from './steamAPIModeEnum';

export interface SteamApplicationConfiguration {
  /** Steam API modes. */
  apiMode?: SteamAPIModeEnum;
  buttonText?: string;
  clientId?: string;
  scope?: string;
  webAPIKey?: string;
  data?: Record<string, unknown>;
  createRegistration?: boolean;
}

export const steamApplicationConfigurationSchema: Schema<SteamApplicationConfiguration> = object(
  {
    apiMode: ['apiMode', optional(steamAPIModeEnumSchema)],
    buttonText: ['buttonText', optional(string())],
    clientId: ['client_id', optional(string())],
    scope: ['scope', optional(string())],
    webAPIKey: ['webAPIKey', optional(string())],
    data: ['data', optional(dict(unknown()))],
    createRegistration: ['createRegistration', optional(boolean())],
  }
);
