/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface SystemLogsExportRequest {
  includeArchived?: boolean;
  lastNBytes?: number;
  dateTimeSecondsFormat?: string;
  /** Timezone Identifier */
  zoneId?: string;
}

export const systemLogsExportRequestSchema: Schema<SystemLogsExportRequest> = object(
  {
    includeArchived: ['includeArchived', optional(boolean())],
    lastNBytes: ['lastNBytes', optional(number())],
    dateTimeSecondsFormat: ['dateTimeSecondsFormat', optional(string())],
    zoneId: ['zoneId', optional(string())],
  }
);
