/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SystemConfiguration,
  systemConfigurationSchema,
} from './systemConfiguration';

/** Response for the system configuration API. */
export interface SystemConfigurationResponse {
  systemConfiguration?: SystemConfiguration;
}

export const systemConfigurationResponseSchema: Schema<SystemConfigurationResponse> = object(
  {
    systemConfiguration: [
      'systemConfiguration',
      optional(lazy(() => systemConfigurationSchema)),
    ],
  }
);
