/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  RateLimitedRequestConfiguration,
  rateLimitedRequestConfigurationSchema,
} from './rateLimitedRequestConfiguration';

export interface TenantRateLimitConfiguration {
  failedLogin?: RateLimitedRequestConfiguration;
  forgotPassword?: RateLimitedRequestConfiguration;
  sendEmailVerification?: RateLimitedRequestConfiguration;
  sendPasswordless?: RateLimitedRequestConfiguration;
  sendRegistrationVerification?: RateLimitedRequestConfiguration;
  sendTwoFactor?: RateLimitedRequestConfiguration;
}

export const tenantRateLimitConfigurationSchema: Schema<TenantRateLimitConfiguration> = object(
  {
    failedLogin: [
      'failedLogin',
      optional(lazy(() => rateLimitedRequestConfigurationSchema)),
    ],
    forgotPassword: [
      'forgotPassword',
      optional(lazy(() => rateLimitedRequestConfigurationSchema)),
    ],
    sendEmailVerification: [
      'sendEmailVerification',
      optional(lazy(() => rateLimitedRequestConfigurationSchema)),
    ],
    sendPasswordless: [
      'sendPasswordless',
      optional(lazy(() => rateLimitedRequestConfigurationSchema)),
    ],
    sendRegistrationVerification: [
      'sendRegistrationVerification',
      optional(lazy(() => rateLimitedRequestConfigurationSchema)),
    ],
    sendTwoFactor: [
      'sendTwoFactor',
      optional(lazy(() => rateLimitedRequestConfigurationSchema)),
    ],
  }
);
