/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  RegistrationUnverifiedOptions,
  registrationUnverifiedOptionsSchema,
} from './registrationUnverifiedOptions';
import {
  UnverifiedBehaviorEnum,
  unverifiedBehaviorEnumSchema,
} from './unverifiedBehaviorEnum';

export interface TenantUnverifiedConfiguration {
  email?: UnverifiedBehaviorEnum;
  whenGated?: RegistrationUnverifiedOptions;
}

export const tenantUnverifiedConfigurationSchema: Schema<TenantUnverifiedConfiguration> = object(
  {
    email: ['email', optional(unverifiedBehaviorEnumSchema)],
    whenGated: [
      'whenGated',
      optional(lazy(() => registrationUnverifiedOptionsSchema)),
    ],
  }
);
