/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TenantFormConfiguration {
  adminUserFormId?: string;
}

export const tenantFormConfigurationSchema: Schema<TenantFormConfiguration> = object(
  { adminUserFormId: ['adminUserFormId', optional(string())] }
);
