/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TenantOAuth2Configuration {
  clientCredentialsAccessTokenPopulateLambdaId?: string;
}

export const tenantOAuth2ConfigurationSchema: Schema<TenantOAuth2Configuration> = object(
  {
    clientCredentialsAccessTokenPopulateLambdaId: [
      'clientCredentialsAccessTokenPopulateLambdaId',
      optional(string()),
    ],
  }
);
