/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { Tenant, tenantSchema } from './tenant';

/** Tenant search response */
export interface TenantSearchResponse {
  tenants?: Tenant[];
  total?: bigint;
}

export const tenantSearchResponseSchema: Schema<TenantSearchResponse> = object({
  tenants: ['tenants', optional(array(lazy(() => tenantSchema)))],
  total: ['total', optional(bigint())],
});
