/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface TenantSSOConfiguration {
  deviceTrustTimeToLiveInSeconds?: number;
}

export const tenantSSOConfigurationSchema: Schema<TenantSSOConfiguration> = object(
  {
    deviceTrustTimeToLiveInSeconds: [
      'deviceTrustTimeToLiveInSeconds',
      optional(number()),
    ],
  }
);
