/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Theme, themeSchema } from './theme';

/** Theme API response object. */
export interface ThemeResponse {
  theme?: Theme;
  themes?: Theme[];
}

export const themeResponseSchema: Schema<ThemeResponse> = object({
  theme: ['theme', optional(lazy(() => themeSchema))],
  themes: ['themes', optional(array(lazy(() => themeSchema)))],
});
