/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Theme, themeSchema } from './theme';

/** Theme API request object. */
export interface ThemeRequest {
  sourceThemeId?: string;
  theme?: Theme;
}

export const themeRequestSchema: Schema<ThemeRequest> = object({
  sourceThemeId: ['sourceThemeId', optional(string())],
  theme: ['theme', optional(lazy(() => themeSchema))],
});
