/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema } from '../schema';

export interface Totals {
  logins?: bigint;
  registrations?: bigint;
  totalRegistrations?: bigint;
}

export const totalsSchema: Schema<Totals> = object({
  logins: ['logins', optional(bigint())],
  registrations: ['registrations', optional(bigint())],
  totalRegistrations: ['totalRegistrations', optional(bigint())],
});
