/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string, unknown } from '../schema';

export interface TwoFactorStartRequest {
  applicationId?: string;
  code?: string;
  loginId?: string;
  state?: Record<string, unknown>;
  trustChallenge?: string;
  userId?: string;
}

export const twoFactorStartRequestSchema: Schema<TwoFactorStartRequest> = object(
  {
    applicationId: ['applicationId', optional(string())],
    code: ['code', optional(string())],
    loginId: ['loginId', optional(string())],
    state: ['state', optional(dict(unknown()))],
    trustChallenge: ['trustChallenge', optional(string())],
    userId: ['userId', optional(string())],
  }
);
