/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';

export interface TwoFactorRequest {
  applicationId?: string;
  authenticatorId?: string;
  code?: string;
  email?: string;
  method?: string;
  mobilePhone?: string;
  secret?: string;
  secretBase32Encoded?: string;
  twoFactorId?: string;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const twoFactorRequestSchema: Schema<TwoFactorRequest> = object({
  applicationId: ['applicationId', optional(string())],
  authenticatorId: ['authenticatorId', optional(string())],
  code: ['code', optional(string())],
  email: ['email', optional(string())],
  method: ['method', optional(string())],
  mobilePhone: ['mobilePhone', optional(string())],
  secret: ['secret', optional(string())],
  secretBase32Encoded: ['secretBase32Encoded', optional(string())],
  twoFactorId: ['twoFactorId', optional(string())],
  eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))],
});
