/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UniqueUsernameStrategyEnum
 */
export enum UniqueUsernameStrategyEnum {
  Always = 'Always',
  OnCollision = 'OnCollision',
}

/**
 * Schema for UniqueUsernameStrategyEnum
 */
export const  uniqueUsernameStrategyEnumSchema: Schema<UniqueUsernameStrategyEnum> = stringEnum(UniqueUsernameStrategyEnum);
