/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnknownScopePolicyEnum
 */
export enum UnknownScopePolicyEnum {
  Allow = 'Allow',
  Remove = 'Remove',
  Reject = 'Reject',
}

/**
 * Schema for UnknownScopePolicyEnum
 */
export const  unknownScopePolicyEnumSchema: Schema<UnknownScopePolicyEnum> = stringEnum(UnknownScopePolicyEnum);
