/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnverifiedBehaviorEnum
 */
export enum UnverifiedBehaviorEnum {
  Allow = 'Allow',
  Gated = 'Gated',
}

/**
 * Schema for UnverifiedBehaviorEnum
 */
export const  unverifiedBehaviorEnumSchema: Schema<UnverifiedBehaviorEnum> = stringEnum(UnverifiedBehaviorEnum);
