/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, object, optional, Schema, string } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';
import { EventTypeEnum, eventTypeEnumSchema } from './eventTypeEnum';
import { TwoFactorMethod, twoFactorMethodSchema } from './twoFactorMethod';
import { User, userSchema } from './user';

/** Model a user event when a two-factor method has been removed. */
export interface UserTwoFactorMethodAddEvent {
  method?: TwoFactorMethod;
  /** The global view of a User. This object contains all global information about the user including birthdate, registration information  preferred languages, global attributes, etc. */
  user?: User;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  createInstant?: bigint;
  id?: string;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  info?: EventInfo;
  tenantId?: string;
  /** Models the event types that FusionAuth produces. */
  type?: EventTypeEnum;
}

export const userTwoFactorMethodAddEventSchema: Schema<UserTwoFactorMethodAddEvent> = object(
  {
    method: ['method', optional(lazy(() => twoFactorMethodSchema))],
    user: ['user', optional(lazy(() => userSchema))],
    createInstant: ['createInstant', optional(bigint())],
    id: ['id', optional(string())],
    info: ['info', optional(lazy(() => eventInfoSchema))],
    tenantId: ['tenantId', optional(string())],
    type: ['type', optional(eventTypeEnumSchema)],
  }
);
