/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

/** Models content user action options. */
export interface UserActionOption {
  /** Models a set of localized Strings that can be stored as JSON. */
  localizedNames?: unknown;
  name?: string;
}

export const userActionOptionSchema: Schema<UserActionOption> = object({
  localizedNames: ['localizedNames', optional(unknown())],
  name: ['name', optional(string())],
});
