/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, lazy, object, optional, Schema } from '../schema';
import { UserComment, userCommentSchema } from './userComment';

/** User comment search response */
export interface UserCommentSearchResponse {
  total?: bigint;
  userComments?: UserComment[];
}

export const userCommentSearchResponseSchema: Schema<UserCommentSearchResponse> = object(
  {
    total: ['total', optional(bigint())],
    userComments: [
      'userComments',
      optional(array(lazy(() => userCommentSchema))),
    ],
  }
);
