/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { SortField, sortFieldSchema } from './sortField';

/** This class is the user query. It provides a build pattern as well as public fields for use on forms and in actions. */
export interface UserSearchCriteria {
  accurateTotal?: boolean;
  ids?: string[];
  nextResults?: string;
  query?: string;
  queryString?: string;
  sortFields?: SortField[];
}

export const userSearchCriteriaSchema: Schema<UserSearchCriteria> = object({
  accurateTotal: ['accurateTotal', optional(boolean())],
  ids: ['ids', optional(array(string()))],
  nextResults: ['nextResults', optional(string())],
  query: ['query', optional(string())],
  queryString: ['queryString', optional(string())],
  sortFields: ['sortFields', optional(array(lazy(() => sortFieldSchema)))],
});
