/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, dict, lazy, object, optional, Schema, string } from '../schema';
import { User, userSchema } from './user';

/** User API response object. */
export interface UserResponse {
  emailVerificationId?: string;
  emailVerificationOneTimeCode?: string;
  registrationVerificationIds?: Record<string, string>;
  registrationVerificationOneTimeCodes?: Record<string, string>;
  token?: string;
  /** The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC. */
  tokenExpirationInstant?: bigint;
  /** The global view of a User. This object contains all global information about the user including birthdate, registration information  preferred languages, global attributes, etc. */
  user?: User;
}

export const userResponseSchema: Schema<UserResponse> = object({
  emailVerificationId: ['emailVerificationId', optional(string())],
  emailVerificationOneTimeCode: [
    'emailVerificationOneTimeCode',
    optional(string()),
  ],
  registrationVerificationIds: [
    'registrationVerificationIds',
    optional(dict(string())),
  ],
  registrationVerificationOneTimeCodes: [
    'registrationVerificationOneTimeCodes',
    optional(dict(string())),
  ],
  token: ['token', optional(string())],
  tokenExpirationInstant: ['tokenExpirationInstant', optional(bigint())],
  user: ['user', optional(lazy(() => userSchema))],
});
