/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';
import { User, userSchema } from './user';

/** User API request object. */
export interface UserRequest {
  applicationId?: string;
  currentPassword?: string;
  disableDomainBlock?: boolean;
  sendSetPasswordEmail?: boolean;
  skipVerification?: boolean;
  /** The global view of a User. This object contains all global information about the user including birthdate, registration information  preferred languages, global attributes, etc. */
  user?: User;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const userRequestSchema: Schema<UserRequest> = object({
  applicationId: ['applicationId', optional(string())],
  currentPassword: ['currentPassword', optional(string())],
  disableDomainBlock: ['disableDomainBlock', optional(boolean())],
  sendSetPasswordEmail: ['sendSetPasswordEmail', optional(boolean())],
  skipVerification: ['skipVerification', optional(boolean())],
  user: ['user', optional(lazy(() => userSchema))],
  eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))],
});
