/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { UserConsent, userConsentSchema } from './userConsent';

/** API response for User consent. */
export interface UserConsentResponse {
  /** Models a User consent. */
  userConsent?: UserConsent;
  userConsents?: UserConsent[];
}

export const userConsentResponseSchema: Schema<UserConsentResponse> = object({
  userConsent: ['userConsent', optional(lazy(() => userConsentSchema))],
  userConsents: [
    'userConsents',
    optional(array(lazy(() => userConsentSchema))),
  ],
});
