/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { User, userSchema } from './user';

/** Models the User Login event that is suspicious. */
export interface UserLoginSuspiciousEvent {
  threatsDetected?: unknown[];
  applicationId?: string;
  authenticationType?: string;
  connectorId?: string;
  identityProviderId?: string;
  identityProviderName?: string;
  ipAddress?: string;
  /** The global view of a User. This object contains all global information about the user including birthdate, registration information  preferred languages, global attributes, etc. */
  user?: User;
}

export const userLoginSuspiciousEventSchema: Schema<UserLoginSuspiciousEvent> = object(
  {
    threatsDetected: ['threatsDetected', optional(array(unknown()))],
    applicationId: ['applicationId', optional(string())],
    authenticationType: ['authenticationType', optional(string())],
    connectorId: ['connectorId', optional(string())],
    identityProviderId: ['identityProviderId', optional(string())],
    identityProviderName: ['identityProviderName', optional(string())],
    ipAddress: ['ipAddress', optional(string())],
    user: ['user', optional(lazy(() => userSchema))],
  }
);
