/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UserVerificationRequirementEnum
 */
export enum UserVerificationRequirementEnum {
  Required = 'required',
  Preferred = 'preferred',
  Discouraged = 'discouraged',
}

/**
 * Schema for UserVerificationRequirementEnum
 */
export const  userVerificationRequirementEnumSchema: Schema<UserVerificationRequirementEnum> = stringEnum(UserVerificationRequirementEnum);
