/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import { EventInfo, eventInfoSchema } from './eventInfo';

/** User API delete request object for a single user. */
export interface UserDeleteSingleRequest {
  hardDelete?: boolean;
  /** Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc). */
  eventInfo?: EventInfo;
}

export const userDeleteSingleRequestSchema: Schema<UserDeleteSingleRequest> = object(
  {
    hardDelete: ['hardDelete', optional(boolean())],
    eventInfo: ['eventInfo', optional(lazy(() => eventInfoSchema))],
  }
);
