/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { UserActionReason, userActionReasonSchema } from './userActionReason';

/** User Action Reason API request object. */
export interface UserActionReasonRequest {
  /** Models action reasons. */
  userActionReason?: UserActionReason;
}

export const userActionReasonRequestSchema: Schema<UserActionReasonRequest> = object(
  {
    userActionReason: [
      'userActionReason',
      optional(lazy(() => userActionReasonSchema)),
    ],
  }
);
