/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface UsernameModeration {
  applicationId?: string;
  enabled?: boolean;
}

export const usernameModerationSchema: Schema<UsernameModeration> = object({
  applicationId: ['applicationId', optional(string())],
  enabled: ['enabled', optional(boolean())],
});
