/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

/** User API bulk response object. */
export interface UserDeleteResponse {
  dryRun?: boolean;
  hardDelete?: boolean;
  total?: number;
  userIds?: string[];
}

export const userDeleteResponseSchema: Schema<UserDeleteResponse> = object({
  dryRun: ['dryRun', optional(boolean())],
  hardDelete: ['hardDelete', optional(boolean())],
  total: ['total', optional(number())],
  userIds: ['userIds', optional(array(string()))],
});
