/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface VerifyRegistrationResponse {
  oneTimeCode?: string;
  verificationId?: string;
}

export const verifyRegistrationResponseSchema: Schema<VerifyRegistrationResponse> = object(
  {
    oneTimeCode: ['oneTimeCode', optional(string())],
    verificationId: ['verificationId', optional(string())],
  }
);
