/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface VerifyEmailResponse {
  oneTimeCode?: string;
  verificationId?: string;
}

export const verifyEmailResponseSchema: Schema<VerifyEmailResponse> = object({
  oneTimeCode: ['oneTimeCode', optional(string())],
  verificationId: ['verificationId', optional(string())],
});
