/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VerificationStrategyEnum
 */
export enum VerificationStrategyEnum {
  ClickableLink = 'ClickableLink',
  FormField = 'FormField',
}

/**
 * Schema for VerificationStrategyEnum
 */
export const  verificationStrategyEnumSchema: Schema<VerificationStrategyEnum> = stringEnum(VerificationStrategyEnum);
