/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface VersionResponse {
  version?: string;
}

export const versionResponseSchema: Schema<VersionResponse> = object({
  version: ['version', optional(string())],
});
