/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The <i>authenticator's<i> response for the authentication ceremony in its encoded format */
export interface WebAuthnAuthenticatorAuthenticationResponse {
  authenticatorData?: string;
  clientDataJSON?: string;
  signature?: string;
  userHandle?: string;
}

export const webAuthnAuthenticatorAuthenticationResponseSchema: Schema<WebAuthnAuthenticatorAuthenticationResponse> = object(
  {
    authenticatorData: ['authenticatorData', optional(string())],
    clientDataJSON: ['clientDataJSON', optional(string())],
    signature: ['signature', optional(string())],
    userHandle: ['userHandle', optional(string())],
  }
);
