/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** Options to request extensions during credential registration */
export interface WebAuthnRegistrationExtensionOptions {
  credProps?: boolean;
}

export const webAuthnRegistrationExtensionOptionsSchema: Schema<WebAuthnRegistrationExtensionOptions> = object(
  { credProps: ['credProps', optional(boolean())] }
);
