/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  WebAuthnPublicKeyRegistrationRequest,
  webAuthnPublicKeyRegistrationRequestSchema,
} from './webAuthnPublicKeyRegistrationRequest';

/** Request to complete the WebAuthn registration ceremony for a new credential,. */
export interface WebAuthnRegisterCompleteRequest {
  /** Request to register a new public key with WebAuthn */
  credential?: WebAuthnPublicKeyRegistrationRequest;
  origin?: string;
  rpId?: string;
  userId?: string;
}

export const webAuthnRegisterCompleteRequestSchema: Schema<WebAuthnRegisterCompleteRequest> = object(
  {
    credential: [
      'credential',
      optional(lazy(() => webAuthnPublicKeyRegistrationRequestSchema)),
    ],
    origin: ['origin', optional(string())],
    rpId: ['rpId', optional(string())],
    userId: ['userId', optional(string())],
  }
);
