/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  WebAuthnWorkflowEnum,
  webAuthnWorkflowEnumSchema,
} from './webAuthnWorkflowEnum';

/** API request to start a WebAuthn registration ceremony */
export interface WebAuthnRegisterStartRequest {
  displayName?: string;
  name?: string;
  userAgent?: string;
  userId?: string;
  /** Identifies the WebAuthn workflow. This will affect the parameters used for credential creation  and request based on the Tenant configuration. */
  workflow?: WebAuthnWorkflowEnum;
}

export const webAuthnRegisterStartRequestSchema: Schema<WebAuthnRegisterStartRequest> = object(
  {
    displayName: ['displayName', optional(string())],
    name: ['name', optional(string())],
    userAgent: ['userAgent', optional(string())],
    userId: ['userId', optional(string())],
    workflow: ['workflow', optional(webAuthnWorkflowEnumSchema)],
  }
);
