/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  PublicKeyCredentialCreationOptions,
  publicKeyCredentialCreationOptionsSchema,
} from './publicKeyCredentialCreationOptions';

/** API response for starting a WebAuthn registration ceremony */
export interface WebAuthnRegisterStartResponse {
  /** Allows the Relying Party to specify desired attributes of a new credential. */
  options?: PublicKeyCredentialCreationOptions;
}

export const webAuthnRegisterStartResponseSchema: Schema<WebAuthnRegisterStartResponse> = object(
  {
    options: [
      'options',
      optional(lazy(() => publicKeyCredentialCreationOptionsSchema)),
    ],
  }
);
