/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  CredentialPropertiesOutput,
  credentialPropertiesOutputSchema,
} from './credentialPropertiesOutput';

/** Contains extension output for requested extensions during a WebAuthn ceremony */
export interface WebAuthnExtensionsClientOutputs {
  /** Contains the output for the {@code credProps} extension */
  credProps?: CredentialPropertiesOutput;
}

export const webAuthnExtensionsClientOutputsSchema: Schema<WebAuthnExtensionsClientOutputs> = object(
  {
    credProps: [
      'credProps',
      optional(lazy(() => credentialPropertiesOutputSchema)),
    ],
  }
);
