/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  WebAuthnCredential,
  webAuthnCredentialSchema,
} from './webAuthnCredential';

/** WebAuthn Credential API response */
export interface WebAuthnCredentialResponse {
  /** A User's WebAuthnCredential. Contains all data required to complete WebAuthn authentication ceremonies. */
  credential?: WebAuthnCredential;
  credentials?: WebAuthnCredential[];
}

export const webAuthnCredentialResponseSchema: Schema<WebAuthnCredentialResponse> = object(
  {
    credential: ['credential', optional(lazy(() => webAuthnCredentialSchema))],
    credentials: [
      'credentials',
      optional(array(lazy(() => webAuthnCredentialSchema))),
    ],
  }
);
