/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  WebAuthnAuthenticatorAuthenticationResponse,
  webAuthnAuthenticatorAuthenticationResponseSchema,
} from './webAuthnAuthenticatorAuthenticationResponse';
import {
  WebAuthnExtensionsClientOutputs,
  webAuthnExtensionsClientOutputsSchema,
} from './webAuthnExtensionsClientOutputs';

/** Request to authenticate with WebAuthn */
export interface WebAuthnPublicKeyAuthenticationRequest {
  /** Contains extension output for requested extensions during a WebAuthn ceremony */
  clientExtensionResults?: WebAuthnExtensionsClientOutputs;
  id?: string;
  rpId?: string;
  /** The <i>authenticator's<i> response for the authentication ceremony in its encoded format */
  response?: WebAuthnAuthenticatorAuthenticationResponse;
  type?: string;
}

export const webAuthnPublicKeyAuthenticationRequestSchema: Schema<WebAuthnPublicKeyAuthenticationRequest> = object(
  {
    clientExtensionResults: [
      'clientExtensionResults',
      optional(lazy(() => webAuthnExtensionsClientOutputsSchema)),
    ],
    id: ['id', optional(string())],
    rpId: ['rpId', optional(string())],
    response: [
      'response',
      optional(lazy(() => webAuthnAuthenticatorAuthenticationResponseSchema)),
    ],
    type: ['type', optional(string())],
  }
);
