/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import {
  WebAuthnCredential,
  webAuthnCredentialSchema,
} from './webAuthnCredential';

/** API request to import an existing WebAuthn credential(s) */
export interface WebAuthnCredentialImportRequest {
  credentials?: WebAuthnCredential[];
  validateDbConstraints?: boolean;
}

export const webAuthnCredentialImportRequestSchema: Schema<WebAuthnCredentialImportRequest> = object(
  {
    credentials: [
      'credentials',
      optional(array(lazy(() => webAuthnCredentialSchema))),
    ],
    validateDbConstraints: ['validateDbConstraints', optional(boolean())],
  }
);
