/**
 * FusionAuth APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  WebhookSearchCriteria,
  webhookSearchCriteriaSchema,
} from './webhookSearchCriteria';

/** Search request for webhooks */
export interface WebhookSearchRequest {
  /** Search criteria for webhooks. */
  search?: WebhookSearchCriteria;
}

export const webhookSearchRequestSchema: Schema<WebhookSearchRequest> = object({
  search: ['search', optional(lazy(() => webhookSearchCriteriaSchema))],
});
